package org.domain.sck.entity;

// Generated 04-dic-2012 12:34:55 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * LcredUsuarioNivelEnc generated by hbm2java
 */
@Entity
@Table(name = "lcred_usuario_nivel_enc")
public class LcredUsuarioNivelEnc implements java.io.Serializable {

	private LcredUsuarioNivelEncId id;

	public LcredUsuarioNivelEnc() {
	}

	public LcredUsuarioNivelEnc(LcredUsuarioNivelEncId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idUsuario", column = @Column(name = "id_usuario", nullable = false, length = 20)),
			@AttributeOverride(name = "nombreUsuario", column = @Column(name = "nombre_usuario", length = 200)),
			@AttributeOverride(name = "correo", column = @Column(name = "correo", length = 100)),
			@AttributeOverride(name = "cargo", column = @Column(name = "cargo", length = 3)),
			@AttributeOverride(name = "administrador", column = @Column(name = "administrador", length = 1)),
			@AttributeOverride(name = "envioAutomOtrasSolc", column = @Column(name = "envio_autom_otras_solc", length = 1)) })
	@NotNull
	public LcredUsuarioNivelEncId getId() {
		return this.id;
	}

	public void setId(LcredUsuarioNivelEncId id) {
		this.id = id;
	}

}
