package org.domain.sck.entity;

// Generated 29-05-2012 04:33:41 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * SolicitudMotivoRechazo generated by hbm2java
 */
@Entity
@Table(name = "solicitud_motivo_rechazo")
public class SolicitudMotivoRechazo  {

	private long systemId;
	private Long idSolicitud;
	private LcredMotivoRechazo rechazo;

		
	public SolicitudMotivoRechazo() {
	}

	public SolicitudMotivoRechazo(long systemId) {
		this.systemId = systemId;
	}

	public SolicitudMotivoRechazo(long systemId, Long idSolicitud, LcredMotivoRechazo rechazo) {
		this.systemId = systemId;
		this.idSolicitud = idSolicitud;
		this.rechazo = rechazo;
	}

	@Id
	@GenericGenerator(name="solicitudMotivoRechazoSequenceGenerator", strategy = "org.hibernate.id.enhanced.TableGenerator",
	    parameters = {
			@Parameter(name = "table_name", value = "hibernate_sequences"),
			@Parameter(name = "segment_value", value = "SEQ_SOLICITUD_MOTIVO_RECHAZO"), 
	        @Parameter(name = "initial_value", value = "1"),
	        @Parameter(name = "increment_size", value = "1")
	    }
	)
	@GeneratedValue(generator = "solicitudMotivoRechazoSequenceGenerator")
	@Column(name = "system_id", unique = true, nullable = false, precision = 18, scale = 0,columnDefinition = "numeric(18,0)")
	public long getSystemId() {
		return this.systemId;
	}

	public void setSystemId(long systemId) {
		this.systemId = systemId;
	}

	@Column(name = "solicitud_id", precision = 18, scale = 0)
	public Long getIdSolicitud() {
		return this.idSolicitud;
	}

	public void setIdSolicitud(Long idSolicitud) {
		this.idSolicitud = idSolicitud;
	}
	
		
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "motivo_rechazo_id")	
	public LcredMotivoRechazo getRechazo() {
		return rechazo;
	}

	public void setRechazo(
			LcredMotivoRechazo rechazo) {
		this.rechazo = rechazo;
	}
	
	
}
