package org.domain.sck.entity;

// Generated 09-feb-2013 1:52:07 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;

/**
 * Accion generated by hbm2java
 */
@Entity
@Table(name = "accion")
public class Accion implements java.io.Serializable {

	private String codAccion;
	private String desAccion;

	public Accion() {
	}

	public Accion(String codAccion) {
		this.codAccion = codAccion;
	}

	public Accion(String codAccion, String desAccion) {
		this.codAccion = codAccion;
		this.desAccion = desAccion;
	}

	@Id
	@Column(name = "cod_accion", unique = true, nullable = false, length = 2)
	@Length(max=2)
	public String getCodAccion() {
		return this.codAccion;
	}

	public void setCodAccion(String codAccion) {
		this.codAccion = codAccion;
	}

	@Column(name = "des_accion", length = 50)
	@Length(max = 50)
	public String getDesAccion() {
		return this.desAccion;
	}

	public void setDesAccion(String desAccion) {
		this.desAccion = desAccion;
	}

}
