package org.domain.sck.entity;

// Generated 02-10-2012 09:54:39 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.NotNull;

/**
 * Pantalla generated by hbm2java
 */
@Entity
@Table(name = "pantalla")
public class Pantalla {

	private long idPantalla;
	private String descripcion;
	private String codigo;
	public Pantalla() {
	}

	public Pantalla(long idPantalla, String descripcion, String codigo) {
		this.idPantalla = idPantalla;
		this.descripcion = descripcion;
		this.codigo= codigo;
	}

	@Id
	@GenericGenerator(name = "pantallaSequenceGenerator", strategy = "org.hibernate.id.enhanced.TableGenerator", parameters = {
			@Parameter(name = "table_name", value = "hibernate_sequences"),
			@Parameter(name = "segment_value", value = "SEQ_PANTALLA"),
			@Parameter(name = "initial_value", value = "1"),
			@Parameter(name = "increment_size", value = "1") })
	@GeneratedValue(generator = "pantallaSequenceGenerator")
	@Column(name = "idPantalla", unique = true, nullable = false, precision = 18, scale = 0)
	public Long getIdPantalla() {
		return this.idPantalla;
	}

	public void setIdPantalla(long idPantalla) {
		this.idPantalla = idPantalla;
	}
	

	@Column(name = "descripcion", nullable = false)
	@NotNull
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}


	@Column(name = "codigo", nullable = false, length=50)
	@NotNull
	public String getCodigo() {
		return codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}	

}
