package org.domain.sck.entity;

// Generated 02-10-2012 09:54:39 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.domain.sck.entity.enums.ConceptosType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ZonaSucursalNegocioConcepto generated by hbm2java
 */
@Entity
@Table(name = "zona_sucursal_negocio_concepto")
public class ZonaSucursalNegocioConcepto {

	private long idSystem;
	private PerfilFuncionCanal perfilFuncionCanal;
	private ConceptosType tipoConcepto;
	private String codigo;
	private String descripcion;
	
	public ZonaSucursalNegocioConcepto() {
	}

	public ZonaSucursalNegocioConcepto(long idSystem, PerfilFuncionCanal perfilFuncionCanal, ConceptosType tipoConcepto,
			String codigo, String descripcion  ) {
		this.idSystem = idSystem;
		this.perfilFuncionCanal = perfilFuncionCanal;
		this.tipoConcepto = tipoConcepto;
		this.codigo = codigo;
		this.descripcion = descripcion;
	}

	@Id
	@GenericGenerator(name = "zonaSucursalNegocioConceptoSequenceGenerator", strategy = "org.hibernate.id.enhanced.TableGenerator", parameters = {
			@Parameter(name = "table_name", value = "hibernate_sequences"),
			@Parameter(name = "segment_value", value = "SEQ_ZONA_SUCURSAL_NEGOCIO_CONCEPTO"),
			@Parameter(name = "initial_value", value = "1"),
			@Parameter(name = "increment_size", value = "1") })
	@GeneratedValue(generator = "zonaSucursalNegocioConceptoSequenceGenerator")
	@Column(name = "id_system", unique = true, nullable = false, precision = 18, scale = 0)
	public Long getIdSystem() {
		return this.idSystem;
	}

	public void setIdSystem(long idSystem) {
		this.idSystem = idSystem;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "perfil_funcion_canal", nullable = false)
	@NotNull
	public PerfilFuncionCanal getPerfilFuncionCanal() {
		return perfilFuncionCanal;
	}

	public void setPerfilFuncionCanal(PerfilFuncionCanal perfilFuncionCanal) {
		this.perfilFuncionCanal = perfilFuncionCanal;
	}
	
	@Column(name = "funcion", nullable=true)
	public ConceptosType getTipoConcepto() {
		return tipoConcepto;
	}

	public void setTipoConcepto(ConceptosType tipoConcepto) {
		this.tipoConcepto = tipoConcepto;
	}

	@Column(name = "codigo", nullable=false, length=10)
	@Length(max=10)
	public String getCodigo() {
		return codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descripcion", nullable=false, length=50)
	@Length(max=50)
	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}



}
