package org.domain.sck.entity;

// Generated 01-feb-2013 12:39:20 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;

/**
 * LcredSolicitudProrrogaId generated by hbm2java
 */
@Embeddable
public class LcredSolicitudProrrogaId implements java.io.Serializable {

	private long numSolicitud;
	private String nroCheque;
	private BigDecimal monto;
	private String vencActual;
	private String vencNuevo;

	public LcredSolicitudProrrogaId() {
	}

	public LcredSolicitudProrrogaId(long numSolicitud) {
		this.numSolicitud = numSolicitud;
	}

	public LcredSolicitudProrrogaId(long numSolicitud, String nroCheque,
			BigDecimal monto, String vencActual, String vencNuevo) {
		this.numSolicitud = numSolicitud;
		this.nroCheque = nroCheque;
		this.monto = monto;
		this.vencActual = vencActual;
		this.vencNuevo = vencNuevo;
	}

	@Column(name = "num_solicitud", nullable = false, precision = 18, scale = 0)
	public long getNumSolicitud() {
		return this.numSolicitud;
	}

	public void setNumSolicitud(long numSolicitud) {
		this.numSolicitud = numSolicitud;
	}

	@Column(name = "nro_cheque", length = 20)
	@Length(max = 20)
	public String getNroCheque() {
		return this.nroCheque;
	}

	public void setNroCheque(String nroCheque) {
		this.nroCheque = nroCheque;
	}

	@Column(name = "monto", scale = 4)
	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	@Column(name = "venc_actual", length = 10)
	@Length(max = 10)
	public String getVencActual() {
		return this.vencActual;
	}

	public void setVencActual(String vencActual) {
		this.vencActual = vencActual;
	}

	@Column(name = "venc_nuevo", length = 10)
	@Length(max = 10)
	public String getVencNuevo() {
		return this.vencNuevo;
	}

	public void setVencNuevo(String vencNuevo) {
		this.vencNuevo = vencNuevo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LcredSolicitudProrrogaId))
			return false;
		LcredSolicitudProrrogaId castOther = (LcredSolicitudProrrogaId) other;

		return (this.getNumSolicitud() == castOther.getNumSolicitud())
				&& ((this.getNroCheque() == castOther.getNroCheque()) || (this
						.getNroCheque() != null
						&& castOther.getNroCheque() != null && this
						.getNroCheque().equals(castOther.getNroCheque())))
				&& ((this.getMonto() == castOther.getMonto()) || (this
						.getMonto() != null && castOther.getMonto() != null && this
						.getMonto().equals(castOther.getMonto())))
				&& ((this.getVencActual() == castOther.getVencActual()) || (this
						.getVencActual() != null
						&& castOther.getVencActual() != null && this
						.getVencActual().equals(castOther.getVencActual())))
				&& ((this.getVencNuevo() == castOther.getVencNuevo()) || (this
						.getVencNuevo() != null
						&& castOther.getVencNuevo() != null && this
						.getVencNuevo().equals(castOther.getVencNuevo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNumSolicitud();
		result = 37 * result
				+ (getNroCheque() == null ? 0 : this.getNroCheque().hashCode());
		result = 37 * result
				+ (getMonto() == null ? 0 : this.getMonto().hashCode());
		result = 37
				* result
				+ (getVencActual() == null ? 0 : this.getVencActual()
						.hashCode());
		result = 37 * result
				+ (getVencNuevo() == null ? 0 : this.getVencNuevo().hashCode());
		return result;
	}

}
