package org.domain.sck.entity;

// Generated 02-10-2012 09:54:39 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.NotNull;

/**
 * FormaPagoDetalle generated by hbm2java
 */
@Entity
@Table(name = "forma_pago_detalle")
public class FormaPagoDetalle {

	private Long idDetalle;
	private FormaPagoEncabezado encabezado;
	private FormaPago formaPago;
	
	public FormaPagoDetalle() {

	}

	public FormaPagoDetalle(long idDetalle, FormaPagoEncabezado encabezado, FormaPago formaPago) {
		this.idDetalle = idDetalle;
		this.encabezado = encabezado;
		this.formaPago = formaPago;
	}

	@Id
	@GenericGenerator(name = "formaPagoDetSequenceGenerator", strategy = "org.hibernate.id.enhanced.TableGenerator", parameters = {
			@Parameter(name = "table_name", value = "hibernate_sequences"),
			@Parameter(name = "segment_value", value = "SEQ_FORMA_PAGO_DET"),
			@Parameter(name = "initial_value", value = "1"),
			@Parameter(name = "increment_size", value = "1") })
			
			
	@GeneratedValue(generator = "formaPagoDetSequenceGenerator")
	@Column(name = "id_detalle", unique = true, nullable = false, precision = 18, scale = 0)
	public Long getIdDetalle() {
		return idDetalle;
	}

	public void setIdDetalle(Long idDetalle) {
		this.idDetalle = idDetalle;
	}
	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "encabezado_id", nullable = false)
	@NotNull
	public FormaPagoEncabezado getEncabezado() {
		return encabezado;
	}

	public void setEncabezado(FormaPagoEncabezado encabezado) {
		this.encabezado = encabezado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "forma_pago_id", nullable = false)
	@NotNull
	public FormaPago getFormaPago() {
		return formaPago;
	}

	public void setFormaPago(FormaPago formaPago) {
		this.formaPago = formaPago;
	}	


	
	
}
