package org.domain.sck.entity;

// Generated 21-02-2013 02:50:14 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * LcredSolicitudDm generated by hbm2java
 */
@Entity
@Table(name = "lcred_solicitud_dm")
public class LcredSolicitudDm implements java.io.Serializable {

	private LcredSolicitudDmId id;

	public LcredSolicitudDm() {
	}

	public LcredSolicitudDm(LcredSolicitudDmId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "numSolicitud", column = @Column(name = "num_solicitud", nullable = false, precision = 18, scale = 0)),
			@AttributeOverride(name = "rut", column = @Column(name = "rut", length = 12)),
			@AttributeOverride(name = "nombre", column = @Column(name = "nombre", length = 120)),
			@AttributeOverride(name = "oficinaVentas", column = @Column(name = "oficina_ventas", length = 10)),
			@AttributeOverride(name = "zona", column = @Column(name = "zona", length = 10)),
			@AttributeOverride(name = "listaPrecio", column = @Column(name = "lista_precio", length = 10)),
			@AttributeOverride(name = "sector", column = @Column(name = "sector", length = 30)),
			@AttributeOverride(name = "vendTelefono", column = @Column(name = "vend_telefono", length = 12)),
			@AttributeOverride(name = "vendTerreno", column = @Column(name = "vend_terreno", length = 12)),
			@AttributeOverride(name = "cobrador", column = @Column(name = "cobrador", length = 12)),
			@AttributeOverride(name = "condExpedicion", column = @Column(name = "cond_expedicion", length = 5)),
			@AttributeOverride(name = "condPago", column = @Column(name = "cond_pago", length = 5)) })
	@NotNull
	public LcredSolicitudDmId getId() {
		return this.id;
	}

	public void setId(LcredSolicitudDmId id) {
		this.id = id;
	}

}
