package org.domain.sck.entity;

// Generated 29-05-2012 04:33:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Feriado generated by hbm2java
 */
@Entity
@Table(name = "feriado")
public class Feriado  {

	private long systemId;
	private Date fecha;
	private Long anno;
	private boolean disabled;

	public Feriado() {
		disabled = false;

	}

	public Feriado(long systemId) {
		this.systemId = systemId;
	}

	@Id
	@GenericGenerator(name="feriadoSequenceGenerator", strategy = "org.hibernate.id.enhanced.TableGenerator",
	    parameters = {
			@Parameter(name = "table_name", value = "hibernate_sequences"),
			@Parameter(name = "segment_value", value = "SEQ_FERIADO"), 
	        @Parameter(name = "initial_value", value = "1"),
	        @Parameter(name = "increment_size", value = "1")
	    }
	)
	@GeneratedValue(generator = "feriadoSequenceGenerator")
	@Column(name = "system_id", unique = true, nullable = false, precision = 18, scale = 0,columnDefinition = "numeric(18,0)")
	public long getSystemId() {
		return this.systemId;
	}

	public void setSystemId(long systemId) {
		this.systemId = systemId;
	}


	@Column(name = "fecha", nullable = false)	
	public Date getFecha() {
		return fecha;
	}
	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}
	
	@Column(name = "anno", precision = 4, scale = 0)
	public Long getAnno() {
		return this.anno;
	}

	public void setAnno(Long anno) {
		this.anno = anno;
	}
	
	@Column(name = "disabled", nullable = false)
	public boolean isDisabled() {
		return disabled;
	}
	
	public void setDisabled(boolean disabled) {
		this.disabled = disabled;
	}
	
}
