package org.domain.sck.entity;

// Generated 29-05-2012 04:33:41 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ConceptoNegocio generated by hbm2java
 */
@Entity
@Table(name = "cotizacion_pedido_concepto")
public class CotizacionPedidoConcepto {

	private long systemId;
	private CotizacionPedidoNegocio cotizacionPedidoNegocio;
	private String codigoConcepto;
	private String desConcepto;
	private Double margenPoderado;
	private Long montoMasIva;
	private Double margencConcepto;
	private Double margenPorcePorConcepto;




	public CotizacionPedidoConcepto() {
	}

	public CotizacionPedidoConcepto(long systemId,String codigoConcepto, String desconcepto, 
			Double margenPoderado, Long montoMasIva, CotizacionPedidoNegocio cotizacionPedidoNegocio,Double margencConcepto,Double margenPorcePorConcepto) {
		this.codigoConcepto = codigoConcepto;
		this.desConcepto = desconcepto;
		this.systemId = systemId;
		this.cotizacionPedidoNegocio = cotizacionPedidoNegocio;
		this.margencConcepto = margencConcepto;
		this.margenPoderado = margenPoderado;
		this.montoMasIva = montoMasIva;
		this.margenPorcePorConcepto = margenPorcePorConcepto;
	}

	
	@Id
	@GenericGenerator(name="cotpedConceptoSequenceGenerator", strategy = "org.hibernate.id.enhanced.TableGenerator",
	    parameters = {
			@Parameter(name = "table_name", value = "hibernate_sequences"),
			@Parameter(name = "segment_value", value = "SEQ_COTIZACION_PEDIDO_CONCEPTO"), 
	        @Parameter(name = "initial_value", value = "1"),
	        @Parameter(name = "increment_size", value = "1")
	    }
	)
	@GeneratedValue(generator = "cotpedConceptoSequenceGenerator")
	@Column(name = "system_id", unique = true, nullable = false, precision = 18, scale = 0,columnDefinition = "numeric(18,0)")
	public long getSystemId() {
		return this.systemId;
	}

	public void setSystemId(long systemId) {
		this.systemId = systemId;
	}

	@Column(name = "codigo_concepto", nullable = false, length = 3)
	@NotNull
	@Length(max = 3)
	public String getCodigoConcepto() {
		return this.codigoConcepto;
	}

	public void setCodigoConcepto(String codigoConcepto) {
		this.codigoConcepto = codigoConcepto;
	}

	@Column(name = "des_concepto", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getDesConcepto() {
		return this.desConcepto;
	}

	public void setDesConcepto(String desConcepto) {
		this.desConcepto = desConcepto;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cotizacion_pedido_negocio_id")	
	public CotizacionPedidoNegocio getCotizacionPedidoNegocio() {
		return cotizacionPedidoNegocio;
	}

	public void setCotizacionPedidoNegocio(CotizacionPedidoNegocio CotizacionPedidoNegocio) {
		this.cotizacionPedidoNegocio = CotizacionPedidoNegocio;
	}

	
	@Column(name = "margen_poderado", precision = 18, scale = 0, columnDefinition = "numeric(18,3)")
	public Double getMargenPoderado() {
		return margenPoderado;
	}
	
	public void setMargenPoderado(Double margenPoderado) {
		this.margenPoderado = margenPoderado;
	}
	
	
	@Column(name = "margen_concepto", precision = 18, scale = 0, columnDefinition = "numeric(18,3)")
	public Double getMargenConcepto() {
		return margencConcepto;
	}
	
	public void setMargenConcepto(Double margencConcepto) {
		this.margencConcepto = margencConcepto;
	}	

	@Column(name = "monto_mas_iva", precision = 18, scale = 0)
	public Long getMontoMasIva() {
		return montoMasIva;
	}
	
	public void setMontoMasIva(Long montoMasIva) {
		this.montoMasIva = montoMasIva;
	}	
	
	@Column(name = "margen_porce_por_concepto", precision = 18, scale = 0, columnDefinition = "numeric(18,3)")
	public Double getMargenPorcePorConcepto() {
		return margenPorcePorConcepto;
	}
	
	public void setMargenPorcePorConcepto(Double margenPorcePorConcepto) {
		this.margenPorcePorConcepto = margenPorcePorConcepto;
	}
	
}
