package org.domain.sck.entity;

// Generated 29-ago-2012 13:51:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * LcredCargos generated by hbm2java
 */
@Entity
@Table(name = "lcred_cargos")
public class LcredCargos implements java.io.Serializable {

	private String codCargo;
	private String desCargo;
	private Long nivelCargo;
	private Long nivelSiguiente;
	private String detalleZona;
	private String detalleSucursal;
	private String detalleNegocio;
	private String detalleConcepto;
	private String indBorrado;

	public LcredCargos() {
	}

	public LcredCargos(String codCargo) {
		this.codCargo = codCargo;
	}

	public LcredCargos(String codCargo, String desCargo, Long nivelCargo,
			Long nivelSiguiente, String detalleZona,
			String detalleSucursal, String detalleNegocio,
			String detalleConcepto, String indBorrado) {
		this.codCargo = codCargo;
		this.desCargo = desCargo;
		this.nivelCargo = nivelCargo;
		this.nivelSiguiente = nivelSiguiente;
		this.detalleZona = detalleZona;
		this.detalleSucursal = detalleSucursal;
		this.detalleNegocio = detalleNegocio;
		this.detalleConcepto = detalleConcepto;
		this.indBorrado = indBorrado;
	}

	@Id
	@Column(name = "cod_cargo", unique = true, nullable = false, length = 3)
	@NotNull
	@Length(max = 3)
	public String getCodCargo() {
		return this.codCargo;
	}

	public void setCodCargo(String codCargo) {
		this.codCargo = codCargo;
	}

	@Column(name = "des_cargo", length = 50)
	@Length(max = 50)
	public String getDesCargo() {
		return this.desCargo;
	}

	public void setDesCargo(String desCargo) {
		this.desCargo = desCargo;
	}

	@Column(name = "nivel_cargo", precision = 18, scale = 0)
	public Long getNivelCargo() {
		return this.nivelCargo;
	}

	public void setNivelCargo(Long nivelCargo) {
		this.nivelCargo = nivelCargo;
	}

	@Column(name = "nivel_siguiente", precision = 18, scale = 0)
	public Long getNivelSiguiente() {
		return this.nivelSiguiente;
	}

	public void setNivelSiguiente(Long nivelSiguiente) {
		this.nivelSiguiente = nivelSiguiente;
	}

	@Column(name = "detalle_zona", length = 1)
	public String getDetalleZona() {
		return this.detalleZona;
	}

	public void setDetalleZona(String detalleZona) {
		this.detalleZona = detalleZona;
	}

	@Column(name = "detalle_sucursal", length = 1)
	public String getDetalleSucursal() {
		return this.detalleSucursal;
	}

	public void setDetalleSucursal(String detalleSucursal) {
		this.detalleSucursal = detalleSucursal;
	}

	@Column(name = "detalle_negocio", length = 1)
	public String getDetalleNegocio() {
		return this.detalleNegocio;
	}

	public void setDetalleNegocio(String detalleNegocio) {
		this.detalleNegocio = detalleNegocio;
	}

	@Column(name = "detalle_concepto", length = 1)
	public String getDetalleConcepto() {
		return this.detalleConcepto;
	}

	public void setDetalleConcepto(String detalleConcepto) {
		this.detalleConcepto = detalleConcepto;
	}

	@Column(name = "ind_borrado", length = 1)
	public String getIndBorrado() {
		return this.indBorrado;
	}

	public void setIndBorrado(String indBorrado) {
		this.indBorrado = indBorrado;
	}

}
