package org.domain.sck.entity;

// Generated 29-05-2012 04:33:41 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.Length;

/**
 * DetalleCp generated by hbm2java
 */
@Entity
@Table(name = "detalle_cp")
public class DetalleCp {

	private long systemId;
	private CotizacionPedidoConcepto cotizacionPedidoConcepto;
	@Transient private ConceptosNegocio conceptosNegocio;
	private String codigoArticulo;
	private String nombre;
	private Long monto;
	private Double margen;
	private Double margProdProc;
	private Double margenesMultiplicado;

	public DetalleCp() {
	}

	public DetalleCp(long systemId) {
		this.systemId = systemId;
	}

	public DetalleCp(long systemId, CotizacionPedidoConcepto cotizacionPedidoConcepto,
			String nombre, Long monto, Double margen, Double margProdProc, Double margenesMultiplicado, String codigoArticulo) {
		this.systemId = systemId;
		this.cotizacionPedidoConcepto = cotizacionPedidoConcepto;
		this.monto = monto;
		this.margen = margen;
		this.margProdProc = margProdProc;
		this.nombre = nombre;
		this.margenesMultiplicado = margenesMultiplicado;
		this.codigoArticulo = codigoArticulo;
	}

	@Id
	@GenericGenerator(name="detalleCPSequenceGenerator", strategy = "org.hibernate.id.enhanced.TableGenerator",
	    parameters = {
			@Parameter(name = "table_name", value = "hibernate_sequences"),
			@Parameter(name = "segment_value", value = "SEQ_DETALLE_CP"), 
	        @Parameter(name = "initial_value", value = "1"),
	        @Parameter(name = "increment_size", value = "1")
	    }
	)
	@GeneratedValue(generator = "detalleCPSequenceGenerator")
	@Column(name = "system_id", unique = true, nullable = false, precision = 18, scale = 0,columnDefinition = "numeric(18,0)")
	public long getSystemId() {
		return this.systemId;
	}

	public void setSystemId(long systemId) {
		this.systemId = systemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cotizacion_pedido_concepto_id", columnDefinition = "numeric(18,0)")
	public CotizacionPedidoConcepto getCotizacionPedidoConcepto() {
		return this.cotizacionPedidoConcepto;
	}

	public void setCotizacionPedidoConcepto(CotizacionPedidoConcepto cotizacionPedidoConcepto) {
		this.cotizacionPedidoConcepto = cotizacionPedidoConcepto;
	}
	

	@Column(name = "monto", precision = 18, scale = 0)
	public Long getMonto() {
		return this.monto;
	}

	public void setMonto(Long monto) {
		this.monto = monto;
	}

	@Column(name = "margen", precision = 18, scale = 0,columnDefinition = "numeric(18,3)")
	public Double getMargen() {
		return this.margen;
	}

	public void setMargen(Double margen) {
		this.margen = margen;
	}

	@Column(name = "marg_prod_proc", precision = 18, scale = 0, columnDefinition = "numeric(18,3)")
	public Double getMargProdProc() {
		return this.margProdProc;
	}

	public void setMargProdProc(Double margProdProc) {
		this.margProdProc = margProdProc;
	}
	
	@Column(name = "nombre", nullable = true, length = 100)
	@Length(max=100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "margen_multiplicado", precision = 18, scale = 0, columnDefinition = "numeric(18,3)")
	public Double getMargenesMultiplicado() {
		return this.margenesMultiplicado;
	}

	public void setMargenesMultiplicado(Double margenesMultiplicado) {
		this.margenesMultiplicado = margenesMultiplicado;
	}
	
	@Transient
	public ConceptosNegocio getConceptosNegocio() {
		return conceptosNegocio;
	}
	@Transient
	public void setConceptosNegocio(ConceptosNegocio conceptosNegocio) {
		this.conceptosNegocio = conceptosNegocio;
	}
	
	@Column(name = "codigo_articulo", nullable = true, length = 100)
	@Length(max=100)
	public String getCodigoArticulo() {
		return this.codigoArticulo;
	}

	public void setCodigoArticulo(String codigoArticulo) {
		this.codigoArticulo = codigoArticulo;
	}
	
}
