package org.domain.sck.entity;

// Generated 02-10-2012 09:54:39 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.NotNull;

/**
 * TipoPantalla generated by hbm2java
 */
@Entity
@Table(name = "tipo_pantalla")
public class TipoPantalla {

	private Long idTipoPantalla;
	private TipoUsuario tipoUsuario;
	private Pantalla pantalla;

	public TipoPantalla() {
	}

	public TipoPantalla(long idTipoPantalla, TipoUsuario tipoUsuario, Pantalla pantalla) {
		this.idTipoPantalla = idTipoPantalla;
		this.pantalla = pantalla;
		this.tipoUsuario = tipoUsuario;
	}

	@Id
	@GenericGenerator(name = "tipoPantallaSequenceGenerator", strategy = "org.hibernate.id.enhanced.TableGenerator", parameters = {
			@Parameter(name = "table_name", value = "hibernate_sequences"),
			@Parameter(name = "segment_value", value = "SEQ_TIPO_PANTALLA"),
			@Parameter(name = "initial_value", value = "1"),
			@Parameter(name = "increment_size", value = "1") })
			
			
	@GeneratedValue(generator = "tipoPantallaSequenceGenerator")
	@Column(name = "idTipoPantalla", unique = true, nullable = false, precision = 18, scale = 0)
	public Long getIdTipoPantalla() {
		return idTipoPantalla;
	}

	public void setIdTipoPantalla(Long idTipoPantalla) {
		this.idTipoPantalla = idTipoPantalla;
	}
	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipoUsuario_id", nullable = false)
	@NotNull
	public TipoUsuario getTipoUsuario() {
		return tipoUsuario;
	}

	public void setTipoUsuario(TipoUsuario tipoUsuario) {
		this.tipoUsuario = tipoUsuario;
	}

	
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pantalla_id", nullable = false)
	@NotNull
	public Pantalla getPantalla() {
		return pantalla;
	}

	public void setPantalla(Pantalla pantalla) {
		this.pantalla = pantalla;
	}
	
	
}
