package org.domain.sck.entity;

// Generated 02-10-2012 09:54:39 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * LogsCorreos generated by hbm2java
 */
@Entity
@Table(name = "logs_correos")
public class LogsCorreos {

	private Long idSystem;
	private String solicitud;
	private String asunto;
	private String contenido;
	private String destinatarios;
	private String estado;
	private String accion;

	
	public LogsCorreos() {
	}

	public LogsCorreos(long idSystem, String solicitud, String asunto, String contenido, String destinatarios, String estado,String accion ) {
		this.idSystem = idSystem;
		this.solicitud = solicitud;
		this.asunto = asunto;
		this.contenido = contenido;
		this.destinatarios = destinatarios;
		this.estado = estado;
		this.accion = accion;
	}

	@Id
	@GenericGenerator(name = "logsCorreosSequenceGenerator", strategy = "org.hibernate.id.enhanced.TableGenerator", parameters = {
			@Parameter(name = "table_name", value = "hibernate_sequences"),
			@Parameter(name = "segment_value", value = "SEQ_LOGS_CORREOS"),
			@Parameter(name = "initial_value", value = "1"),
			@Parameter(name = "increment_size", value = "1") })
			
			
	@GeneratedValue(generator = "logsCorreosSequenceGenerator")
	@Column(name = "id_logs_correo", unique = true, nullable = false, precision = 18, scale = 0, columnDefinition = "numeric(18,0)")
	public Long getIdSystem() {
		return idSystem;
	}

	public void setIdSystem(Long idSystem) {
		this.idSystem = idSystem;
	}

	
	@Column(name = "solicitud", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getSolicitud() {
		return solicitud;
	}
	public void setSolicitud(String solicitud) {
		this.solicitud = solicitud;
	}
	
	@Column(name = "asunto", nullable = false, length = 10000)
	@NotNull
	@Length(max = 10000)
	public String getAsunto() {
		return asunto;
	}
	public void setAsunto(String asunto) {
		this.asunto = asunto;
	}
	
	
	@Column(name = "contenido", nullable = false, length = 10000)
	@NotNull
	@Length(max = 10000)
	public String getContenido() {
		return contenido;
	}
	public void setContenido(String contenido) {
		this.contenido = contenido;
	}

	
	@Column(name = "destinatarios", nullable = false, length = 10000)
	@NotNull
	@Length(max = 10000)
	public String getDestinatarios() {
		return destinatarios;
	}
	public void setDestinatarios(String destinatarios) {
		this.destinatarios = destinatarios;
	}

	
	@Column(name = "estado", nullable = false, length = 5)
	@NotNull
	@Length(max = 5)
	public String getEstado() {
		return estado;
	}
	public void setEstado(String estado) {
		this.estado = estado;
	}
	

	@Column(name = "accion", nullable = false, length = 10000)
	@NotNull
	@Length(max = 10000)
	public String getAccion() {
		return accion;
	}
	public void setAccion(String accion) {
		this.accion = accion;
	}
		
	
	
	
	
}
