package org.domain.sck.entity;

// Generated 09-feb-2013 1:52:07 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;

/**
 * Estados generated by hbm2java
 */
@Entity
@Table(name = "estados")
public class Estados implements java.io.Serializable {

	private char codEstado;
	private String desEstado;

	public Estados() {
	}

	public Estados(char codEstado) {
		this.codEstado = codEstado;
	}

	public Estados(char codEstado, String desEstado) {
		this.codEstado = codEstado;
		this.desEstado = desEstado;
	}

	@Id
	@Column(name = "cod_estado", unique = true, nullable = false, length = 2)
	public char getCodEstado() {
		return this.codEstado;
	}

	public void setCodEstado(char codEstado) {
		this.codEstado = codEstado;
	}

	@Column(name = "des_estado", length = 50)
	@Length(max = 50)
	public String getDesEstado() {
		return this.desEstado;
	}

	public void setDesEstado(String desEstado) {
		this.desEstado = desEstado;
	}

}
