package org.domain.sck.entity;

// Generated 17-ene-2013 12:02:26 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ConceptosNegocio generated by hbm2java
 */
@Entity
@Table(name = "ConceptosNegocios")
public class ConceptosNegocio {

	private long systemId;
	private String concepto;
	private String desNegocio;
	private String descripcion;
	private Integer estaSolo;
	private String jerarquia;
	private String negocio;
	private Integer orden;
	private Integer ordenDiv;

	public ConceptosNegocio() {
	}

	public ConceptosNegocio(long systemId, String concepto, String desNegocio,
			String descripcion, String negocio) {
		this.systemId = systemId;
		this.concepto = concepto;
		this.desNegocio = desNegocio;
		this.descripcion = descripcion;
		this.negocio = negocio;
	}

	public ConceptosNegocio(long systemId, String concepto, String desNegocio,
			String descripcion, Integer estaSolo, String jerarquia,
			String negocio, Integer orden, Integer ordenDiv) {
		this.systemId = systemId;
		this.concepto = concepto;
		this.desNegocio = desNegocio;
		this.descripcion = descripcion;
		this.estaSolo = estaSolo;
		this.jerarquia = jerarquia;
		this.negocio = negocio;
		this.orden = orden;
		this.ordenDiv = ordenDiv;
	}

	@Id
	@Column(name = "system_id", unique = true, nullable = false, precision = 18, scale = 0)
	public long getSystemId() {
		return this.systemId;
	}

	public void setSystemId(long systemId) {
		this.systemId = systemId;
	}

	@Column(name = "Concepto", nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}

	@Column(name = "Des_Negocio", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getDesNegocio() {
		return this.desNegocio;
	}

	public void setDesNegocio(String desNegocio) {
		this.desNegocio = desNegocio;
	}

	@Column(name = "Descripcion", nullable = false, length = 30)
	@NotNull
	@Length(max = 30)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "EstaSolo")
	public Integer getEstaSolo() {
		return this.estaSolo;
	}

	public void setEstaSolo(Integer estaSolo) {
		this.estaSolo = estaSolo;
	}

	@Column(name = "Jerarquia", length = 10)
	@Length(max = 10)
	public String getJerarquia() {
		return this.jerarquia;
	}

	public void setJerarquia(String jerarquia) {
		this.jerarquia = jerarquia;
	}

	@Column(name = "Negocio", nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getNegocio() {
		return this.negocio;
	}

	public void setNegocio(String negocio) {
		this.negocio = negocio;
	}

	@Column(name = "Orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Column(name = "Orden_Div")
	public Integer getOrdenDiv() {
		return this.ordenDiv;
	}

	public void setOrdenDiv(Integer ordenDiv) {
		this.ordenDiv = ordenDiv;
	}

}
