package org.domain.sck.entity;

// Generated 29-05-2012 04:33:41 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ConceptoNegocio generated by hbm2java
 */
@Entity
@Table(name = "cotizacion_pedido_negocio")
public class CotizacionPedidoNegocio {

	private long systemId;
	private CotizacionPedido cotizacionPedido;
	private String negocio;
	private String desNegocio;
	private Double margenNegocio;
	private Double representacion;



	public CotizacionPedidoNegocio() {
	}

	public CotizacionPedidoNegocio(long systemId, String negocio, String desNegocio,
			String concepto, String descripcion, CotizacionPedido cotizacionPedido, Double margenNegocio, Double representacion) {
		this.negocio = negocio;
		this.desNegocio = desNegocio;
		this.systemId = systemId;
		this.cotizacionPedido = cotizacionPedido;
		this.margenNegocio = margenNegocio;
		this.representacion = representacion;
	}

	
	@Id
	@GenericGenerator(name="cotpedNegocioSequenceGenerator", strategy = "org.hibernate.id.enhanced.TableGenerator",
	    parameters = {
			@Parameter(name = "table_name", value = "hibernate_sequences"),
			@Parameter(name = "segment_value", value = "SEQ_COTIZACION_PEDIDO_NEGOCIO"), 
	        @Parameter(name = "initial_value", value = "1"),
	        @Parameter(name = "increment_size", value = "1")
	    }
	)
	@GeneratedValue(generator = "cotpedNegocioSequenceGenerator")
	@Column(name = "system_id", unique = true, nullable = false, precision = 18, scale = 0,columnDefinition = "numeric(18,0)")
	public long getSystemId() {
		return this.systemId;
	}

	public void setSystemId(long systemId) {
		this.systemId = systemId;
	}

	@Column(name = "Negocio", nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getNegocio() {
		return this.negocio;
	}

	public void setNegocio(String negocio) {
		this.negocio = negocio;
	}

	@Column(name = "Des_Negocio", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getDesNegocio() {
		return this.desNegocio;
	}

	public void setDesNegocio(String desNegocio) {
		this.desNegocio = desNegocio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cotizacion_pedido_id")	
	public CotizacionPedido getCotizacionPedido() {
		return cotizacionPedido;
	}

	public void setCotizacionPedido(CotizacionPedido cotizacionPedido) {
		this.cotizacionPedido = cotizacionPedido;
	}

	
	@Column(name = "margen_negocio", precision = 18, nullable = false, scale = 0,columnDefinition = "numeric(18,3)")
	public Double getMargenNegocio() {
		return margenNegocio;
	}
	
	public void setMargenNegocio(Double margenNegocio) {
		this.margenNegocio = margenNegocio;
	}
	
	@Column(name = "representacion", precision = 18, nullable = false, scale = 0,columnDefinition = "numeric(18,3)")
	public Double getRepresentacion() {
		return representacion;
	}
	
	public void setRepresentacion(Double representacion) {
		this.representacion = representacion;
	}	
	
	
}
