package org.domain.sck.entity;

// Generated 29-05-2012 04:33:41 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * CotizacionPedido generated by hbm2java
 */
@Entity
@Table(name = "cotizacion_pedido")
public class CotizacionPedido  {

	private long systemId;
	private CotizacionPedidoCabecera cotizacionPedidoCabecera;
	private Long NCotiPed;
	private Double margenGlobal;

	

	
	public CotizacionPedido() {
	}

	public CotizacionPedido(long systemId) {
		this.systemId = systemId;
	}

	public CotizacionPedido(long systemId,  Long NCotiPed, CotizacionPedidoCabecera cotizacionPedidoCabecera, Double margenGlobal) {
		this.systemId = systemId;
		this.NCotiPed = NCotiPed;
		this.cotizacionPedidoCabecera = cotizacionPedidoCabecera;
		this.margenGlobal = margenGlobal;
	}

	@Id
	@GenericGenerator(name="cotizacionPedidoSequenceGenerator", strategy = "org.hibernate.id.enhanced.TableGenerator",
	    parameters = {
			@Parameter(name = "table_name", value = "hibernate_sequences"),
			@Parameter(name = "segment_value", value = "SEQ_COTIZACION_PEDIDO"), 
	        @Parameter(name = "initial_value", value = "1"),
	        @Parameter(name = "increment_size", value = "1")
	    }
	)
	@GeneratedValue(generator = "cotizacionPedidoSequenceGenerator")
	@Column(name = "system_id", unique = true, nullable = false, precision = 18, scale = 0,columnDefinition = "numeric(18,0)")
	public long getSystemId() {
		return this.systemId;
	}

	public void setSystemId(long systemId) {
		this.systemId = systemId;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cot_ped_cab_id")	
	public CotizacionPedidoCabecera getCotizacionPedidoCabecera() {
		return cotizacionPedidoCabecera;
	}

	public void setCotizacionPedidoCabecera(
			CotizacionPedidoCabecera cotizacionPedidoCabecera) {
		this.cotizacionPedidoCabecera = cotizacionPedidoCabecera;
	}
	

	@Column(name = "n_coti_ped", precision = 18, scale = 0)
	public Long getNCotiPed() {
		return this.NCotiPed;
	}

	public void setNCotiPed(Long NCotiPed) {
		this.NCotiPed = NCotiPed;
	}

	
	@Column(name = "margen_global", precision = 18, scale = 0,columnDefinition = "numeric(18,3)")
	public Double getMargenGlobal() {
		return margenGlobal;
	}
	
	public void setMargenGlobal(Double margenGlobal) {
		this.margenGlobal = margenGlobal;
	}	
	
	
}
