package org.domain.sck.entity;

// Generated 29-05-2012 04:33:41 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Time;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Jornada generated by hbm2java
 */
@Entity
@Table(name = "jornada")
public class Jornada  {

	private long systemId;
	private Time horaInicial;
	private Time horaFinal;
	private boolean disabled;

	public Jornada() {
		disabled = false;

	}

	public Jornada(long systemId) {
		this.systemId = systemId;
	}

	@Id
	@GenericGenerator(name="jornadaSequenceGenerator", strategy = "org.hibernate.id.enhanced.TableGenerator",
	    parameters = {
			@Parameter(name = "table_name", value = "hibernate_sequences"),
			@Parameter(name = "segment_value", value = "SEQ_JORNADA"), 
	        @Parameter(name = "initial_value", value = "1"),
	        @Parameter(name = "increment_size", value = "1")
	    }
	)
	@GeneratedValue(generator = "jornadaSequenceGenerator")
	@Column(name = "system_id", unique = true, nullable = false, precision = 18, scale = 0,columnDefinition = "numeric(18,0)")
	public long getSystemId() {
		return this.systemId;
	}

	public void setSystemId(long systemId) {
		this.systemId = systemId;
	}


	@Column(name = "horaInicial", nullable = false)
	public Time getHoraInicial() {
		return horaInicial;
	}
	
	public void setHoraInicial(Time horaInicial) {
		this.horaInicial = horaInicial;
	}
	
	@Column(name = "horaFinal", nullable = false)
	public Time getHoraFinal() {
		return horaFinal;
	}
	
	public void setHoraFinal(Time horaFinal) {
		this.horaFinal = horaFinal;
	}
	
	@Column(name = "disabled", nullable = false)
	public boolean isDisabled() {
		return disabled;
	}
	
	public void setDisabled(boolean disabled) {
		this.disabled = disabled;
	}
	
}
