package org.domain.sck.entity;

// Generated 29-ene-2013 14:50:35 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * LcredSolicitudBloqueos generated by hbm2java
 */
@Entity
@Table(name = "lcred_solicitud_bloqueos")
public class LcredSolicitudBloqueos implements Serializable {

	private Long numSolicitud;
	private String motivoBloqDesbloq;
	private String observacionesFinal;
	private String usuarioAnalisis;
	private Date fechaAnalisis;
	private Date horaAnalisis;

	public LcredSolicitudBloqueos() {
	}

	public LcredSolicitudBloqueos(Long numSolicitud) {
		this.numSolicitud = numSolicitud;
	}

	public LcredSolicitudBloqueos(Long numSolicitud,
			String motivoBloqDesbloq, String observacionesFinal,
			String usuarioAnalisis, Date fechaAnalisis, Date horaAnalisis) {
		this.numSolicitud = numSolicitud;
		this.motivoBloqDesbloq = motivoBloqDesbloq;
		this.observacionesFinal = observacionesFinal;
		this.usuarioAnalisis = usuarioAnalisis;
		this.fechaAnalisis = fechaAnalisis;
		this.horaAnalisis = horaAnalisis;
	}

	@Id
	@Column(name = "num_solicitud", unique = true, nullable = false)
	@NotNull
	public Long getNumSolicitud() {
		return this.numSolicitud;
	}

	public void setNumSolicitud(Long numSolicitud) {
		this.numSolicitud = numSolicitud;
	}

	@Column(name = "motivo_bloq_desbloq")
	public String getMotivoBloqDesbloq() {
		return this.motivoBloqDesbloq;
	}

	public void setMotivoBloqDesbloq(String motivoBloqDesbloq) {
		this.motivoBloqDesbloq = motivoBloqDesbloq;
	}

	@Column(name = "observaciones_final")
	public String getObservacionesFinal() {
		return this.observacionesFinal;
	}

	public void setObservacionesFinal(String observacionesFinal) {
		this.observacionesFinal = observacionesFinal;
	}

	@Column(name = "usuario_analisis", length = 50)
	@Length(max = 50)
	public String getUsuarioAnalisis() {
		return this.usuarioAnalisis;
	}

	public void setUsuarioAnalisis(String usuarioAnalisis) {
		this.usuarioAnalisis = usuarioAnalisis;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_analisis", length = 23)
	public Date getFechaAnalisis() {
		return this.fechaAnalisis;
	}

	public void setFechaAnalisis(Date fechaAnalisis) {
		this.fechaAnalisis = fechaAnalisis;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hora_analisis", length = 23)
	public Date getHoraAnalisis() {
		return this.horaAnalisis;
	}

	public void setHoraAnalisis(Date horaAnalisis) {
		this.horaAnalisis = horaAnalisis;
	}

}
