package org.domain.sck.entity;

// Generated 24-ene-2013 16:19:38 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * LcredSolicitudLcredito generated by hbm2java
 */
@Entity
@Table(name = "lcred_solicitud_lcredito")
public class LcredSolicitudLcredito implements Serializable {

	private long numSolicitud;
	private String codTipoSolicitud;
	private String statusSolicitud;
	private Character opcionNormalInicial;
	private BigDecimal montoNormalInicial;
	private Character opcionCreditoInicial;
	private BigDecimal montoCreditoInicial;
	private String opcionNormalFinal;
	private BigDecimal montoNormalFinal;
	private String opcionCreditoFinal;
	private BigDecimal montoCreditoFinal;
	private String observacionesInicial;
	private String observacionesFinal;
	private String usuarioAnalisis;
	private Date fechaAnalisis;
	private Date horaAnalisis;
	private String motivoRechazo;
	private String observacionesRechazo;
	private String condRiesgoInicial;
	private String condRiesgoFinal;
	private String condPagoInicial;
	private String condPagoFinal;
	private String dpDescripcionProyecto;
	private String dpMonto;
	private String dpPlazoEjecucion;
	private String dpPotencialCompra;
	private String dpConceptosInvoluc;
	private String dpSocios;
	private String centroCosto;

	public LcredSolicitudLcredito() {
	}

	public LcredSolicitudLcredito(long numSolicitud, String codTipoSolicitud) {
		this.numSolicitud = numSolicitud;
		this.codTipoSolicitud = codTipoSolicitud;
	}

	public LcredSolicitudLcredito(long numSolicitud, String codTipoSolicitud,
			String statusSolicitud, Character opcionNormalInicial,
			BigDecimal montoNormalInicial, Character opcionCreditoInicial,
			BigDecimal montoCreditoInicial, String opcionNormalFinal,
			BigDecimal montoNormalFinal, String opcionCreditoFinal,
			BigDecimal montoCreditoFinal, String observacionesInicial,
			String observacionesFinal, String usuarioAnalisis,
			Date fechaAnalisis, Date horaAnalisis, String motivoRechazo,
			String observacionesRechazo, String condRiesgoInicial,
			String condRiesgoFinal, String condPagoInicial,
			String condPagoFinal, String dpDescripcionProyecto,
			String dpMonto, String dpPlazoEjecucion, String dpPotencialCompra,
			String dpConceptosInvoluc, String dpSocios,
			String centroCosto) {
		this.numSolicitud = numSolicitud;
		this.codTipoSolicitud = codTipoSolicitud;
		this.statusSolicitud = statusSolicitud;
		this.opcionNormalInicial = opcionNormalInicial;
		this.montoNormalInicial = montoNormalInicial;
		this.opcionCreditoInicial = opcionCreditoInicial;
		this.montoCreditoInicial = montoCreditoInicial;
		this.opcionNormalFinal = opcionNormalFinal;
		this.montoNormalFinal = montoNormalFinal;
		this.opcionCreditoFinal = opcionCreditoFinal;
		this.montoCreditoFinal = montoCreditoFinal;
		this.observacionesInicial = observacionesInicial;
		this.observacionesFinal = observacionesFinal;
		this.usuarioAnalisis = usuarioAnalisis;
		this.fechaAnalisis = fechaAnalisis;
		this.horaAnalisis = horaAnalisis;
		this.motivoRechazo = motivoRechazo;
		this.observacionesRechazo = observacionesRechazo;
		this.condRiesgoInicial = condRiesgoInicial;
		this.condRiesgoFinal = condRiesgoFinal;
		this.condPagoInicial = condPagoInicial;
		this.condPagoFinal = condPagoFinal;
		this.dpDescripcionProyecto = dpDescripcionProyecto;
		this.dpMonto = dpMonto;
		this.dpPlazoEjecucion = dpPlazoEjecucion;
		this.dpPotencialCompra = dpPotencialCompra;
		this.dpConceptosInvoluc = dpConceptosInvoluc;
		this.dpSocios = dpSocios;
		this.centroCosto = centroCosto;
	}

	@Id
	@Column(name = "num_solicitud", unique = true, nullable = false, precision = 18, scale = 0)
	public long getNumSolicitud() {
		return this.numSolicitud;
	}

	public void setNumSolicitud(long numSolicitud) {
		this.numSolicitud = numSolicitud;
	}

	@Column(name = "cod_tipo_solicitud", nullable = false, length = 3)
	@NotNull
	@Length(max = 3)
	public String getCodTipoSolicitud() {
		return this.codTipoSolicitud;
	}

	public void setCodTipoSolicitud(String codTipoSolicitud) {
		this.codTipoSolicitud = codTipoSolicitud;
	}

	@Column(name = "status_solicitud", length = 2)
	@Length(max = 2)
	public String getStatusSolicitud() {
		return this.statusSolicitud;
	}

	public void setStatusSolicitud(String statusSolicitud) {
		this.statusSolicitud = statusSolicitud;
	}

	@Column(name = "opcion_normal_inicial", length = 1)
	public Character getOpcionNormalInicial() {
		return this.opcionNormalInicial;
	}

	public void setOpcionNormalInicial(Character opcionNormalInicial) {
		this.opcionNormalInicial = opcionNormalInicial;
	}

	@Column(name = "monto_normal_inicial", scale = 4)
	public BigDecimal getMontoNormalInicial() {
		return this.montoNormalInicial;
	}

	public void setMontoNormalInicial(BigDecimal montoNormalInicial) {
		this.montoNormalInicial = montoNormalInicial;
	}

	@Column(name = "opcion_credito_inicial", length = 1)
	public Character getOpcionCreditoInicial() {
		return this.opcionCreditoInicial;
	}

	public void setOpcionCreditoInicial(Character opcionCreditoInicial) {
		this.opcionCreditoInicial = opcionCreditoInicial;
	}

	@Column(name = "monto_credito_inicial", scale = 4)
	public BigDecimal getMontoCreditoInicial() {
		return this.montoCreditoInicial;
	}

	public void setMontoCreditoInicial(BigDecimal montoCreditoInicial) {
		this.montoCreditoInicial = montoCreditoInicial;
	}

	@Column(name = "opcion_normal_final")
	public String getOpcionNormalFinal() {
		return this.opcionNormalFinal;
	}

	public void setOpcionNormalFinal(String opcionNormalFinal) {
		this.opcionNormalFinal = opcionNormalFinal;
	}

	@Column(name = "monto_normal_final", scale = 4)
	public BigDecimal getMontoNormalFinal() {
		return this.montoNormalFinal;
	}

	public void setMontoNormalFinal(BigDecimal montoNormalFinal) {
		this.montoNormalFinal = montoNormalFinal;
	}

	@Column(name = "opcion_credito_final")
	public String getOpcionCreditoFinal() {
		return this.opcionCreditoFinal;
	}

	public void setOpcionCreditoFinal(String opcionCreditoFinal) {
		this.opcionCreditoFinal = opcionCreditoFinal;
	}

	@Column(name = "monto_credito_final", scale = 4)
	public BigDecimal getMontoCreditoFinal() {
		return this.montoCreditoFinal;
	}

	public void setMontoCreditoFinal(BigDecimal montoCreditoFinal) {
		this.montoCreditoFinal = montoCreditoFinal;
	}

	@Column(name = "observaciones_inicial")
	public String getObservacionesInicial() {
		return this.observacionesInicial;
	}

	public void setObservacionesInicial(String observacionesInicial) {
		this.observacionesInicial = observacionesInicial;
	}

	@Column(name = "observaciones_final")
	public String getObservacionesFinal() {
		return this.observacionesFinal;
	}

	public void setObservacionesFinal(String observacionesFinal) {
		this.observacionesFinal = observacionesFinal;
	}

	@Column(name = "usuario_analisis", length = 15)
	@Length(max = 15)
	public String getUsuarioAnalisis() {
		return this.usuarioAnalisis;
	}

	public void setUsuarioAnalisis(String usuarioAnalisis) {
		this.usuarioAnalisis = usuarioAnalisis;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_analisis", length = 23)
	public Date getFechaAnalisis() {
		return this.fechaAnalisis;
	}

	public void setFechaAnalisis(Date fechaAnalisis) {
		this.fechaAnalisis = fechaAnalisis;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hora_analisis", length = 23)
	public Date getHoraAnalisis() {
		return this.horaAnalisis;
	}

	public void setHoraAnalisis(Date horaAnalisis) {
		this.horaAnalisis = horaAnalisis;
	}

	@Column(name = "motivo_rechazo", length = 100)
	@Length(max = 100)
	public String getMotivoRechazo() {
		return this.motivoRechazo;
	}

	public void setMotivoRechazo(String motivoRechazo) {
		this.motivoRechazo = motivoRechazo;
	}

	@Column(name = "observaciones_rechazo")
	public String getObservacionesRechazo() {
		return this.observacionesRechazo;
	}

	public void setObservacionesRechazo(String observacionesRechazo) {
		this.observacionesRechazo = observacionesRechazo;
	}

	@Column(name = "cond_riesgo_inicial", length = 5)
	@Length(max = 5)
	public String getCondRiesgoInicial() {
		return this.condRiesgoInicial;
	}

	public void setCondRiesgoInicial(String condRiesgoInicial) {
		this.condRiesgoInicial = condRiesgoInicial;
	}

	@Column(name = "cond_riesgo_final", length = 5)
	@Length(max = 5)
	public String getCondRiesgoFinal() {
		return this.condRiesgoFinal;
	}

	public void setCondRiesgoFinal(String condRiesgoFinal) {
		this.condRiesgoFinal = condRiesgoFinal;
	}

	@Column(name = "cond_pago_inicial", length = 5)
	@Length(max = 5)
	public String getCondPagoInicial() {
		return this.condPagoInicial;
	}

	public void setCondPagoInicial(String condPagoInicial) {
		this.condPagoInicial = condPagoInicial;
	}

	@Column(name = "cond_pago_final", length = 5)
	@Length(max = 5)
	public String getCondPagoFinal() {
		return this.condPagoFinal;
	}

	public void setCondPagoFinal(String condPagoFinal) {
		this.condPagoFinal = condPagoFinal;
	}

	@Column(name = "dp_descripcion_proyecto")
	public String getDpDescripcionProyecto() {
		return this.dpDescripcionProyecto;
	}

	public void setDpDescripcionProyecto(String dpDescripcionProyecto) {
		this.dpDescripcionProyecto = dpDescripcionProyecto;
	}

	@Column(name = "dp_monto", length = 50)
	@Length(max = 50)
	public String getDpMonto() {
		return this.dpMonto;
	}

	public void setDpMonto(String dpMonto) {
		this.dpMonto = dpMonto;
	}

	@Column(name = "dp_plazo_ejecucion", length = 100)
	@Length(max = 100)
	public String getDpPlazoEjecucion() {
		return this.dpPlazoEjecucion;
	}

	public void setDpPlazoEjecucion(String dpPlazoEjecucion) {
		this.dpPlazoEjecucion = dpPlazoEjecucion;
	}

	@Column(name = "dp_potencial_compra", length = 100)
	@Length(max = 100)
	public String getDpPotencialCompra() {
		return this.dpPotencialCompra;
	}

	public void setDpPotencialCompra(String dpPotencialCompra) {
		this.dpPotencialCompra = dpPotencialCompra;
	}

	@Column(name = "dp_conceptos_involuc")
	public String getDpConceptosInvoluc() {
		return this.dpConceptosInvoluc;
	}

	public void setDpConceptosInvoluc(String dpConceptosInvoluc) {
		this.dpConceptosInvoluc = dpConceptosInvoluc;
	}

	@Column(name = "dp_socios")
	public String getDpSocios() {
		return this.dpSocios;
	}

	public void setDpSocios(String dpSocios) {
		this.dpSocios = dpSocios;
	}

	@Column(name = "centro_costo", length = 50)
	@Length(max = 50)
	public String getCentroCosto() {
		return this.centroCosto;
	}

	public void setCentroCosto(String centroCosto) {
		this.centroCosto = centroCosto;
	}

}
