package org.domain.sck.entity;

// Generated 20-feb-2013 12:24:31 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * LcredTraficoEstados generated by hbm2java
 */
@Entity
@Table(name = "lcred_trafico_estados")
public class LcredTraficoEstados implements java.io.Serializable {

	private LcredTraficoEstadosId id;

	public LcredTraficoEstados() {
	}

	public LcredTraficoEstados(LcredTraficoEstadosId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "numSolicitud", column = @Column(name = "num_solicitud", nullable = false, precision = 18, scale = 0)),
			@AttributeOverride(name = "secuencia", column = @Column(name = "secuencia", nullable = false, precision = 18, scale = 0)),
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", nullable = false, length = 23)),
			@AttributeOverride(name = "hora", column = @Column(name = "hora", nullable = false, length = 23)),
			@AttributeOverride(name = "proceso", column = @Column(name = "proceso", length = 1)),
			@AttributeOverride(name = "usuarioOrigen", column = @Column(name = "usuario_origen", length = 20)),
			@AttributeOverride(name = "estadoOrigen", column = @Column(name = "estado_origen", length = 2)),
			@AttributeOverride(name = "usuarioDestino", column = @Column(name = "usuario_destino", nullable = false, length = 20)),
			@AttributeOverride(name = "estadoDestino", column = @Column(name = "estado_destino", length = 2)),
			@AttributeOverride(name = "usuarioActual", column = @Column(name = "usuario_actual", length = 20)),
			@AttributeOverride(name = "nivelPerfil", column = @Column(name = "nivel_perfil", precision = 18, scale = 0)) })
	@NotNull
	public LcredTraficoEstadosId getId() {
		return this.id;
	}

	public void setId(LcredTraficoEstadosId id) {
		this.id = id;
	}

}
