package org.domain.sck.entity;

// Generated 20-feb-2013 12:24:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * LcredTraficoEstadosId generated by hbm2java
 */
@Embeddable
public class LcredTraficoEstadosId implements java.io.Serializable {

	private long numSolicitud;
	private long secuencia;
	private Date fecha;
	private Date hora;
	private Character proceso;
	private String usuarioOrigen;
	private String estadoOrigen;
	private String usuarioDestino;
	private String estadoDestino;
	private String usuarioActual;
	private Long nivelPerfil;

	public LcredTraficoEstadosId() {
	}

	public LcredTraficoEstadosId(long numSolicitud, long secuencia, Date fecha,
			Date hora, String usuarioDestino) {
		this.numSolicitud = numSolicitud;
		this.secuencia = secuencia;
		this.fecha = fecha;
		this.hora = hora;
		this.usuarioDestino = usuarioDestino;
	}

	public LcredTraficoEstadosId(long numSolicitud, long secuencia, Date fecha,
			Date hora, Character proceso, String usuarioOrigen,
			String estadoOrigen, String usuarioDestino, String estadoDestino,
			String usuarioActual, Long nivelPerfil) {
		this.numSolicitud = numSolicitud;
		this.secuencia = secuencia;
		this.fecha = fecha;
		this.hora = hora;
		this.proceso = proceso;
		this.usuarioOrigen = usuarioOrigen;
		this.estadoOrigen = estadoOrigen;
		this.usuarioDestino = usuarioDestino;
		this.estadoDestino = estadoDestino;
		this.usuarioActual = usuarioActual;
		this.nivelPerfil = nivelPerfil;
	}

	@Column(name = "num_solicitud", nullable = false, precision = 18, scale = 0)
	public long getNumSolicitud() {
		return this.numSolicitud;
	}

	public void setNumSolicitud(long numSolicitud) {
		this.numSolicitud = numSolicitud;
	}

	@Column(name = "secuencia", nullable = false, precision = 18, scale = 0)
	public long getSecuencia() {
		return this.secuencia;
	}

	public void setSecuencia(long secuencia) {
		this.secuencia = secuencia;
	}

	@Column(name = "fecha", nullable = false, length = 23)
	@NotNull
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "hora", nullable = false, length = 23)
	@NotNull
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "proceso", length = 1)
	public Character getProceso() {
		return this.proceso;
	}

	public void setProceso(Character proceso) {
		this.proceso = proceso;
	}

	@Column(name = "usuario_origen", length = 20)
	@Length(max = 20)
	public String getUsuarioOrigen() {
		return this.usuarioOrigen;
	}

	public void setUsuarioOrigen(String usuarioOrigen) {
		this.usuarioOrigen = usuarioOrigen;
	}

	@Column(name = "estado_origen", length = 2)
	@Length(max = 2)
	public String getEstadoOrigen() {
		return this.estadoOrigen;
	}

	public void setEstadoOrigen(String estadoOrigen) {
		this.estadoOrigen = estadoOrigen;
	}

	@Column(name = "usuario_destino", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getUsuarioDestino() {
		return this.usuarioDestino;
	}

	public void setUsuarioDestino(String usuarioDestino) {
		this.usuarioDestino = usuarioDestino;
	}

	@Column(name = "estado_destino", length = 2)
	@Length(max = 2)
	public String getEstadoDestino() {
		return this.estadoDestino;
	}

	public void setEstadoDestino(String estadoDestino) {
		this.estadoDestino = estadoDestino;
	}

	@Column(name = "usuario_actual", length = 20)
	@Length(max = 20)
	public String getUsuarioActual() {
		return this.usuarioActual;
	}

	public void setUsuarioActual(String usuarioActual) {
		this.usuarioActual = usuarioActual;
	}

	@Column(name = "nivel_perfil", precision = 18, scale = 0)
	public Long getNivelPerfil() {
		return this.nivelPerfil;
	}

	public void setNivelPerfil(Long nivelPerfil) {
		this.nivelPerfil = nivelPerfil;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LcredTraficoEstadosId))
			return false;
		LcredTraficoEstadosId castOther = (LcredTraficoEstadosId) other;

		return (this.getNumSolicitud() == castOther.getNumSolicitud())
				&& (this.getSecuencia() == castOther.getSecuencia())
				&& ((this.getFecha() == castOther.getFecha()) || (this
						.getFecha() != null && castOther.getFecha() != null && this
						.getFecha().equals(castOther.getFecha())))
				&& ((this.getHora() == castOther.getHora()) || (this.getHora() != null
						&& castOther.getHora() != null && this.getHora()
						.equals(castOther.getHora())))
				&& ((this.getProceso() == castOther.getProceso()) || (this
						.getProceso() != null && castOther.getProceso() != null && this
						.getProceso().equals(castOther.getProceso())))
				&& ((this.getUsuarioOrigen() == castOther.getUsuarioOrigen()) || (this
						.getUsuarioOrigen() != null
						&& castOther.getUsuarioOrigen() != null && this
						.getUsuarioOrigen()
						.equals(castOther.getUsuarioOrigen())))
				&& ((this.getEstadoOrigen() == castOther.getEstadoOrigen()) || (this
						.getEstadoOrigen() != null
						&& castOther.getEstadoOrigen() != null && this
						.getEstadoOrigen().equals(castOther.getEstadoOrigen())))
				&& ((this.getUsuarioDestino() == castOther.getUsuarioDestino()) || (this
						.getUsuarioDestino() != null
						&& castOther.getUsuarioDestino() != null && this
						.getUsuarioDestino().equals(
								castOther.getUsuarioDestino())))
				&& ((this.getEstadoDestino() == castOther.getEstadoDestino()) || (this
						.getEstadoDestino() != null
						&& castOther.getEstadoDestino() != null && this
						.getEstadoDestino()
						.equals(castOther.getEstadoDestino())))
				&& ((this.getUsuarioActual() == castOther.getUsuarioActual()) || (this
						.getUsuarioActual() != null
						&& castOther.getUsuarioActual() != null && this
						.getUsuarioActual()
						.equals(castOther.getUsuarioActual())))
				&& ((this.getNivelPerfil() == castOther.getNivelPerfil()) || (this
						.getNivelPerfil() != null
						&& castOther.getNivelPerfil() != null && this
						.getNivelPerfil().equals(castOther.getNivelPerfil())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNumSolicitud();
		result = 37 * result + (int) this.getSecuencia();
		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result
				+ (getHora() == null ? 0 : this.getHora().hashCode());
		result = 37 * result
				+ (getProceso() == null ? 0 : this.getProceso().hashCode());
		result = 37
				* result
				+ (getUsuarioOrigen() == null ? 0 : this.getUsuarioOrigen()
						.hashCode());
		result = 37
				* result
				+ (getEstadoOrigen() == null ? 0 : this.getEstadoOrigen()
						.hashCode());
		result = 37
				* result
				+ (getUsuarioDestino() == null ? 0 : this.getUsuarioDestino()
						.hashCode());
		result = 37
				* result
				+ (getEstadoDestino() == null ? 0 : this.getEstadoDestino()
						.hashCode());
		result = 37
				* result
				+ (getUsuarioActual() == null ? 0 : this.getUsuarioActual()
						.hashCode());
		result = 37
				* result
				+ (getNivelPerfil() == null ? 0 : this.getNivelPerfil()
						.hashCode());
		return result;
	}

}
