package org.domain.sck.entity;

// Generated 12-feb-2013 22:24:06 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * LcredSolicitudObservaciones generated by hbm2java
 */
@Entity
@Table(name = "lcred_solicitud_observaciones")
public class LcredSolicitudObservaciones implements java.io.Serializable {

	private LcredSolicitudObservacionesId id;

	public LcredSolicitudObservaciones() {
	}

	public LcredSolicitudObservaciones(LcredSolicitudObservacionesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "numSolicitud", column = @Column(name = "num_solicitud", nullable = false, precision = 18, scale = 0)),
			@AttributeOverride(name = "tipoSol", column = @Column(name = "tipo_sol", length = 10)),
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", nullable = false, length = 23)),
			@AttributeOverride(name = "hora", column = @Column(name = "hora", nullable = false, length = 23)),
			@AttributeOverride(name = "usuario", column = @Column(name = "usuario", length = 20)),
			@AttributeOverride(name = "observacion", column = @Column(name = "observacion")),
			@AttributeOverride(name = "correlativo", column = @Column(name = "correlativo", precision = 18, scale = 0)) })
	@NotNull
	public LcredSolicitudObservacionesId getId() {
		return this.id;
	}

	public void setId(LcredSolicitudObservacionesId id) {
		this.id = id;
	}

}
