package org.domain.sck.entity;

// Generated 08-ene-2013 11:52:16 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * LcredSolicitud generated by hbm2java
 */
@Entity
@Table(name = "lcred_solicitud")
public class LcredSolicitud implements Serializable {

	private LcredSolicitudId id;
	private Date hraSolicitud;
	private String codEmisor;
	private String sucursalEmisor;
	private String rutCliente;
	private String nomCliente;
	private String codSucursal;
	private String dirCliente;
	private String comCliente;
	private String ciuCliente;
	private String telCliente;
	private String faxCliente;
	private Date fechaCreacionCliente;
	private BigDecimal linCredito;
	private BigDecimal linCreditoF;
	private BigDecimal linCreditoS;
	private String clsRiesgo;
	private String conPago;
	private String tipSeguro;
	private String vigSeguro;
	private Character flgEstado;
	private Character flgPrioridad;
	private String glsObservaciones;
	private String codRechazo;
	private Integer prmFacturas;
	private BigDecimal prmVentas;
	private Long mesesVentas;
	private BigDecimal vtaTotal12Meses;
	private Date fecSalida;
	private String estado;
	private Character prioridad;
	private BigDecimal morosidadMonto;
	private Long morosidadNro;
	private BigDecimal protestosMonto;
	private Long protestosNro;
	private Long diasMora;
	private String dm;
	private Long nroRv;
	private String usuarioActual;
	private String tipoSolicitudIncluidas;
	private Long cantidadSolicitudesIncluidas;
	private Long cantidadSolicitudesTratadas;
	private BigDecimal linCreditoDisp;
	private BigDecimal linCreditoFDisp;
	private String productoCompra;
	private String plazoCompra;
	private String motivoCompra;
	private String margenNegocio;
	private String codificacionCheque;
	private String otros;
	private BigDecimal peackCredito;
	private BigDecimal montoAsegurado;
	private BigDecimal riesgoKupfer;
	private BigDecimal montoCuotas;
	private BigDecimal montoNormal;
	private BigDecimal linCreditoUtiliz;
	private BigDecimal linCreditoFUtiliz;
	private String giroCliente;
	private BigDecimal seguroPesos;
	private BigDecimal seguroUf;
	private String estadoLcKh;
	private String estadoLcCuotas;
	private String observAnalista;
	private String observSolicitud;
	private Long secuenciaEjecutivo;
	private Long secuenciaAnalista;
	private Long secuenciaAprobador;
	private String dmSolicitud;
	private String canal;
	private String tipoCliente;
	private String dmVenta;
	private String desTiposol;
	private String tipTiposol;
	private BigDecimal monto;
	private String subTiposol;
	private String usuarioDevuelve;
	private Boolean evaluar;
	private Boolean devolver;
	private Boolean analizar;
	private String formaPago;
	private String horaMinutosSegundos;
	private String estadoEvalaucion;
	private BigDecimal montoRiesgoKupferCalculado;
	private String usuarioVarios;
	private Sociedad sociedad;
	
	public LcredSolicitud() {
	}

	public LcredSolicitud(LcredSolicitudId id, Date hraSolicitud,
			String codEmisor, String rutCliente, String nomCliente,
			String codSucursal, String dirCliente, String comCliente,
			String ciuCliente) {
		this.id = id;
		this.hraSolicitud = hraSolicitud;
		this.codEmisor = codEmisor;
		this.rutCliente = rutCliente;
		this.nomCliente = nomCliente;
		this.codSucursal = codSucursal;
		this.dirCliente = dirCliente;
		this.comCliente = comCliente;
		this.ciuCliente = ciuCliente;
	}

	public LcredSolicitud(LcredSolicitudId id, Date hraSolicitud,
			String codEmisor, String sucursalEmisor, String rutCliente,
			String nomCliente, String codSucursal, String dirCliente,
			String comCliente, String ciuCliente, String telCliente,
			String faxCliente, Date fechaCreacionCliente,
			BigDecimal linCredito, BigDecimal linCreditoF,
			BigDecimal linCreditoS, String clsRiesgo, String conPago,
			String tipSeguro, String vigSeguro, Character flgEstado,
			Character flgPrioridad, String glsObservaciones,
			String codRechazo, Integer prmFacturas, BigDecimal prmVentas,
			Long mesesVentas, BigDecimal vtaTotal12Meses, Date fecSalida,
			String estado, Character prioridad, BigDecimal morosidadMonto,
			Long morosidadNro, BigDecimal protestosMonto, Long protestosNro,
			Long diasMora, String dm, Long nroRv, String usuarioActual,
			String tipoSolicitudIncluidas, Long cantidadSolicitudesIncluidas,
			Long cantidadSolicitudesTratadas, BigDecimal linCreditoDisp,
			BigDecimal linCreditoFDisp, String productoCompra,
			String plazoCompra, String motivoCompra,
			String margenNegocio, String codificacionCheque,
			String otros, BigDecimal peackCredito,
			BigDecimal montoAsegurado, BigDecimal riesgoKupfer,
			BigDecimal montoCuotas, BigDecimal montoNormal,
			BigDecimal linCreditoUtiliz, BigDecimal linCreditoFUtiliz,
			String giroCliente, BigDecimal seguroPesos,
			BigDecimal seguroUf, String estadoLcKh, String estadoLcCuotas,
			String observAnalista, String observSolicitud,
			Long secuenciaEjecutivo, Long secuenciaAnalista,
			Long secuenciaAprobador, String dmSolicitud, String canal,
			String tipoCliente, String dmVenta, String desTiposol,
			String tipTiposol, BigDecimal monto, String subTiposol, Boolean evaluar,
			Boolean devolver, Boolean analizar, String usuarioDevuelve, String formaPago, String horaMinutosSegundos,String estadoEvalaucion
			,String usuarioVarios,Sociedad sociedad) {
		this.id = id;
		this.hraSolicitud = hraSolicitud;
		this.codEmisor = codEmisor;
		this.sucursalEmisor = sucursalEmisor;
		this.rutCliente = rutCliente;
		this.nomCliente = nomCliente;
		this.codSucursal = codSucursal;
		this.dirCliente = dirCliente;
		this.comCliente = comCliente;
		this.ciuCliente = ciuCliente;
		this.telCliente = telCliente;
		this.faxCliente = faxCliente;
		this.fechaCreacionCliente = fechaCreacionCliente;
		this.linCredito = linCredito;
		this.linCreditoF = linCreditoF;
		this.linCreditoS = linCreditoS;
		this.clsRiesgo = clsRiesgo;
		this.conPago = conPago;
		this.tipSeguro = tipSeguro;
		this.vigSeguro = vigSeguro;
		this.flgEstado = flgEstado;
		this.flgPrioridad = flgPrioridad;
		this.glsObservaciones = glsObservaciones;
		this.codRechazo = codRechazo;
		this.prmFacturas = prmFacturas;
		this.prmVentas = prmVentas;
		this.mesesVentas = mesesVentas;
		this.vtaTotal12Meses = vtaTotal12Meses;
		this.fecSalida = fecSalida;
		this.estado = estado;
		this.prioridad = prioridad;
		this.morosidadMonto = morosidadMonto;
		this.morosidadNro = morosidadNro;
		this.protestosMonto = protestosMonto;
		this.protestosNro = protestosNro;
		this.diasMora = diasMora;
		this.dm = dm;
		this.nroRv = nroRv;
		this.usuarioActual = usuarioActual;
		this.tipoSolicitudIncluidas = tipoSolicitudIncluidas;
		this.cantidadSolicitudesIncluidas = cantidadSolicitudesIncluidas;
		this.cantidadSolicitudesTratadas = cantidadSolicitudesTratadas;
		this.linCreditoDisp = linCreditoDisp;
		this.linCreditoFDisp = linCreditoFDisp;
		this.productoCompra = productoCompra;
		this.plazoCompra = plazoCompra;
		this.motivoCompra = motivoCompra;
		this.margenNegocio = margenNegocio;
		this.codificacionCheque = codificacionCheque;
		this.otros = otros;
		this.peackCredito = peackCredito;
		this.montoAsegurado = montoAsegurado;
		this.riesgoKupfer = riesgoKupfer;
		this.montoCuotas = montoCuotas;
		this.montoNormal = montoNormal;
		this.linCreditoUtiliz = linCreditoUtiliz;
		this.linCreditoFUtiliz = linCreditoFUtiliz;
		this.giroCliente = giroCliente;
		this.seguroPesos = seguroPesos;
		this.seguroUf = seguroUf;
		this.estadoLcKh = estadoLcKh;
		this.estadoLcCuotas = estadoLcCuotas;
		this.observAnalista = observAnalista;
		this.observSolicitud = observSolicitud;
		this.secuenciaEjecutivo = secuenciaEjecutivo;
		this.secuenciaAnalista = secuenciaAnalista;
		this.secuenciaAprobador = secuenciaAprobador;
		this.dmSolicitud = dmSolicitud;
		this.canal = canal;
		this.tipoCliente = tipoCliente;
		this.dmVenta = dmVenta;
		this.desTiposol = desTiposol;
		this.tipTiposol = tipTiposol;
		this.monto = monto;
		this.subTiposol = subTiposol;
		this.evaluar = evaluar;
		this.devolver = devolver;
		this.analizar = analizar;
		this.usuarioDevuelve = usuarioDevuelve;
		this.formaPago = formaPago;
		this.horaMinutosSegundos = horaMinutosSegundos;
		this.estadoEvalaucion = estadoEvalaucion;
		this.usuarioVarios = usuarioVarios;
		this.sociedad = sociedad;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "numSolicitud", column = @Column(name = "num_solicitud", nullable = false, precision = 18, scale = 0)),
			@AttributeOverride(name = "fecSolicitud", column = @Column(name = "fec_solicitud", nullable = false, length = 23)) })
	@NotNull
	public LcredSolicitudId getId() {
		return this.id;
	}

	public void setId(LcredSolicitudId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hra_solicitud", nullable = false, length = 23)
	@NotNull
	public Date getHraSolicitud() {
		return this.hraSolicitud;
	}

	public void setHraSolicitud(Date hraSolicitud) {
		this.hraSolicitud = hraSolicitud;
	}

	@Column(name = "cod_emisor", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getCodEmisor() {
		return this.codEmisor;
	}

	public void setCodEmisor(String codEmisor) {
		this.codEmisor = codEmisor;
	}

	@Column(name = "sucursal_emisor", length = 4)
	@Length(max = 4)
	public String getSucursalEmisor() {
		return this.sucursalEmisor;
	}

	public void setSucursalEmisor(String sucursalEmisor) {
		this.sucursalEmisor = sucursalEmisor;
	}

	@Column(name = "rut_cliente", nullable = false, length = 12)
	@NotNull
	@Length(max = 12)
	public String getRutCliente() {
		return this.rutCliente;
	}

	public void setRutCliente(String rutCliente) {
		this.rutCliente = rutCliente;
	}

	@Column(name = "nom_cliente", nullable = false, length = 40)
	@NotNull
	@Length(max = 40)
	public String getNomCliente() {
		return this.nomCliente;
	}

	public void setNomCliente(String nomCliente) {
		this.nomCliente = nomCliente;
	}

	@Column(name = "cod_sucursal", nullable = false, length = 4)
	@NotNull
	@Length(max = 4)
	public String getCodSucursal() {
		return this.codSucursal;
	}

	public void setCodSucursal(String codSucursal) {
		this.codSucursal = codSucursal;
	}

	@Column(name = "dir_cliente", nullable = false, length = 40)
	@NotNull
	@Length(max = 40)
	public String getDirCliente() {
		return this.dirCliente;
	}

	public void setDirCliente(String dirCliente) {
		this.dirCliente = dirCliente;
	}

	@Column(name = "com_cliente", nullable = false, length = 35)
	@NotNull
	@Length(max = 35)
	public String getComCliente() {
		return this.comCliente;
	}

	public void setComCliente(String comCliente) {
		this.comCliente = comCliente;
	}

	@Column(name = "ciu_cliente", nullable = false, length = 35)
	@NotNull
	@Length(max = 35)
	public String getCiuCliente() {
		return this.ciuCliente;
	}

	public void setCiuCliente(String ciuCliente) {
		this.ciuCliente = ciuCliente;
	}

	@Column(name = "tel_cliente", length = 16)
	@Length(max = 16)
	public String getTelCliente() {
		return this.telCliente;
	}

	public void setTelCliente(String telCliente) {
		this.telCliente = telCliente;
	}

	@Column(name = "fax_cliente", length = 31)
	@Length(max = 31)
	public String getFaxCliente() {
		return this.faxCliente;
	}

	public void setFaxCliente(String faxCliente) {
		this.faxCliente = faxCliente;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion_cliente", length = 23)
	public Date getFechaCreacionCliente() {
		return this.fechaCreacionCliente;
	}

	public void setFechaCreacionCliente(Date fechaCreacionCliente) {
		this.fechaCreacionCliente = fechaCreacionCliente;
	}

	@Column(name = "lin_credito", scale = 4)
	public BigDecimal getLinCredito() {
		return this.linCredito;
	}

	public void setLinCredito(BigDecimal linCredito) {
		this.linCredito = linCredito;
	}

	@Column(name = "lin_credito_f", scale = 4)
	public BigDecimal getLinCreditoF() {
		return this.linCreditoF;
	}

	public void setLinCreditoF(BigDecimal linCreditoF) {
		this.linCreditoF = linCreditoF;
	}

	@Column(name = "lin_credito_s", scale = 4)
	public BigDecimal getLinCreditoS() {
		return this.linCreditoS;
	}

	public void setLinCreditoS(BigDecimal linCreditoS) {
		this.linCreditoS = linCreditoS;
	}

	@Column(name = "cls_riesgo", length = 4)
	@Length(max = 4)
	public String getClsRiesgo() {
		return this.clsRiesgo;
	}

	public void setClsRiesgo(String clsRiesgo) {
		this.clsRiesgo = clsRiesgo;
	}

	@Column(name = "con_pago", length = 4)
	@Length(max = 4)
	public String getConPago() {
		return this.conPago;
	}

	public void setConPago(String conPago) {
		this.conPago = conPago;
	}

	@Column(name = "tip_seguro", length = 3)
	@Length(max = 3)
	public String getTipSeguro() {
		return this.tipSeguro;
	}

	public void setTipSeguro(String tipSeguro) {
		this.tipSeguro = tipSeguro;
	}

	@Column(name = "vig_seguro", length = 3)
	@Length(max = 3)
	public String getVigSeguro() {
		return this.vigSeguro;
	}

	public void setVigSeguro(String vigSeguro) {
		this.vigSeguro = vigSeguro;
	}

	@Column(name = "flg_estado", length = 1)
	public Character getFlgEstado() {
		return this.flgEstado;
	}

	public void setFlgEstado(Character flgEstado) {
		this.flgEstado = flgEstado;
	}

	@Column(name = "flg_prioridad", length = 1)
	public Character getFlgPrioridad() {
		return this.flgPrioridad;
	}

	public void setFlgPrioridad(Character flgPrioridad) {
		this.flgPrioridad = flgPrioridad;
	}

	@Column(name = "gls_observaciones")
	public String getGlsObservaciones() {
		return this.glsObservaciones;
	}

	public void setGlsObservaciones(String glsObservaciones) {
		this.glsObservaciones = glsObservaciones;
	}

	@Column(name = "cod_rechazo", length = 3)
	@Length(max = 3)
	public String getCodRechazo() {
		return this.codRechazo;
	}

	public void setCodRechazo(String codRechazo) {
		this.codRechazo = codRechazo;
	}

	@Column(name = "prm_facturas")
	public Integer getPrmFacturas() {
		return this.prmFacturas;
	}

	public void setPrmFacturas(Integer prmFacturas) {
		this.prmFacturas = prmFacturas;
	}

	@Column(name = "prm_ventas", scale = 4)
	public BigDecimal getPrmVentas() {
		return this.prmVentas;
	}

	public void setPrmVentas(BigDecimal prmVentas) {
		this.prmVentas = prmVentas;
	}

	@Column(name = "meses_ventas", precision = 18, scale = 0)
	public Long getMesesVentas() {
		return this.mesesVentas;
	}

	public void setMesesVentas(Long mesesVentas) {
		this.mesesVentas = mesesVentas;
	}

	@Column(name = "vta_total_12_meses", scale = 4)
	public BigDecimal getVtaTotal12Meses() {
		return this.vtaTotal12Meses;
	}

	public void setVtaTotal12Meses(BigDecimal vtaTotal12Meses) {
		this.vtaTotal12Meses = vtaTotal12Meses;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_salida", length = 23)
	public Date getFecSalida() {
		return this.fecSalida;
	}

	public void setFecSalida(Date fecSalida) {
		this.fecSalida = fecSalida;
	}

	@Column(name = "estado", length = 2)
	@Length(max = 2)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "prioridad", length = 1)
	public Character getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(Character prioridad) {
		this.prioridad = prioridad;
	}

	@Column(name = "morosidad_monto", scale = 4)
	public BigDecimal getMorosidadMonto() {
		return this.morosidadMonto;
	}

	public void setMorosidadMonto(BigDecimal morosidadMonto) {
		this.morosidadMonto = morosidadMonto;
	}

	@Column(name = "morosidad_nro", precision = 18, scale = 0)
	public Long getMorosidadNro() {
		return this.morosidadNro;
	}

	public void setMorosidadNro(Long morosidadNro) {
		this.morosidadNro = morosidadNro;
	}

	@Column(name = "protestos_monto", scale = 4)
	public BigDecimal getProtestosMonto() {
		return this.protestosMonto;
	}

	public void setProtestosMonto(BigDecimal protestosMonto) {
		this.protestosMonto = protestosMonto;
	}

	@Column(name = "protestos_nro", precision = 18, scale = 0)
	public Long getProtestosNro() {
		return this.protestosNro;
	}

	public void setProtestosNro(Long protestosNro) {
		this.protestosNro = protestosNro;
	}

	@Column(name = "dias_mora", precision = 18, scale = 0)
	public Long getDiasMora() {
		return this.diasMora;
	}

	public void setDiasMora(Long diasMora) {
		this.diasMora = diasMora;
	}

	@Column(name = "dm", length = 10)
	@Length(max = 10)
	public String getDm() {
		return this.dm;
	}

	public void setDm(String dm) {
		this.dm = dm;
	}

	@Column(name = "nro_rv", precision = 18, scale = 0)
	public Long getNroRv() {
		return this.nroRv;
	}

	public void setNroRv(Long nroRv) {
		this.nroRv = nroRv;
	}
	@Column(name = "usuario_actual", length = 15)
	@Length(max = 15)
	public String getUsuarioActual() {
		return this.usuarioActual;
	}

	public void setUsuarioActual(String usuarioActual) {
		this.usuarioActual = usuarioActual;
	}

	@Column(name = "tipo_solicitud_incluidas", length = 100)
	@Length(max = 100)
	public String getTipoSolicitudIncluidas() {
		return this.tipoSolicitudIncluidas;
	}

	public void setTipoSolicitudIncluidas(String tipoSolicitudIncluidas) {
		this.tipoSolicitudIncluidas = tipoSolicitudIncluidas;
	}

	@Column(name = "cantidad_solicitudes_incluidas", precision = 18, scale = 0)
	public Long getCantidadSolicitudesIncluidas() {
		return this.cantidadSolicitudesIncluidas;
	}

	public void setCantidadSolicitudesIncluidas(
			Long cantidadSolicitudesIncluidas) {
		this.cantidadSolicitudesIncluidas = cantidadSolicitudesIncluidas;
	}

	@Column(name = "cantidad_solicitudes_tratadas", precision = 18, scale = 0)
	public Long getCantidadSolicitudesTratadas() {
		return this.cantidadSolicitudesTratadas;
	}

	public void setCantidadSolicitudesTratadas(Long cantidadSolicitudesTratadas) {
		this.cantidadSolicitudesTratadas = cantidadSolicitudesTratadas;
	}

	@Column(name = "lin_credito_disp", scale = 4)
	public BigDecimal getLinCreditoDisp() {
		return this.linCreditoDisp;
	}

	public void setLinCreditoDisp(BigDecimal linCreditoDisp) {
		this.linCreditoDisp = linCreditoDisp;
	}

	@Column(name = "lin_credito_f_disp", scale = 4)
	public BigDecimal getLinCreditoFDisp() {
		return this.linCreditoFDisp;
	}

	public void setLinCreditoFDisp(BigDecimal linCreditoFDisp) {
		this.linCreditoFDisp = linCreditoFDisp;
	}

	@Column(name = "producto_compra")
	public String getProductoCompra() {
		return this.productoCompra;
	}

	public void setProductoCompra(String productoCompra) {
		this.productoCompra = productoCompra;
	}

	@Column(name = "plazo_compra")
	public String getPlazoCompra() {
		return this.plazoCompra;
	}

	public void setPlazoCompra(String plazoCompra) {
		this.plazoCompra = plazoCompra;
	}

	@Column(name = "motivo_compra")
	public String getMotivoCompra() {
		return this.motivoCompra;
	}

	public void setMotivoCompra(String motivoCompra) {
		this.motivoCompra = motivoCompra;
	}

	@Column(name = "margen_negocio")
	public String getMargenNegocio() {
		return this.margenNegocio;
	}

	public void setMargenNegocio(String margenNegocio) {
		this.margenNegocio = margenNegocio;
	}

	@Column(name = "codificacion_cheque")
	public String getCodificacionCheque() {
		return this.codificacionCheque;
	}

	public void setCodificacionCheque(String codificacionCheque) {
		this.codificacionCheque = codificacionCheque;
	}

	@Column(name = "otros")
	public String getOtros() {
		return this.otros;
	}

	public void setOtros(String otros) {
		this.otros = otros;
	}

	@Column(name = "peack_credito", scale = 4)
	public BigDecimal getPeackCredito() {
		return this.peackCredito;
	}

	public void setPeackCredito(BigDecimal peackCredito) {
		this.peackCredito = peackCredito;
	}

	@Column(name = "monto_asegurado", scale = 4)
	public BigDecimal getMontoAsegurado() {
		return this.montoAsegurado;
	}

	public void setMontoAsegurado(BigDecimal montoAsegurado) {
		this.montoAsegurado = montoAsegurado;
	}

	@Column(name = "riesgo_kupfer", scale = 4)
	public BigDecimal getRiesgoKupfer() {
		return this.riesgoKupfer;
	}

	public void setRiesgoKupfer(BigDecimal riesgoKupfer) {
		this.riesgoKupfer = riesgoKupfer;
	}

	@Column(name = "monto_cuotas", scale = 4)
	public BigDecimal getMontoCuotas() {
		return this.montoCuotas;
	}

	public void setMontoCuotas(BigDecimal montoCuotas) {
		this.montoCuotas = montoCuotas;
	}

	@Column(name = "monto_normal", scale = 4)
	public BigDecimal getMontoNormal() {
		return this.montoNormal;
	}

	public void setMontoNormal(BigDecimal montoNormal) {
		this.montoNormal = montoNormal;
	}

	@Column(name = "lin_credito_utiliz", scale = 4)
	public BigDecimal getLinCreditoUtiliz() {
		return this.linCreditoUtiliz;
	}

	public void setLinCreditoUtiliz(BigDecimal linCreditoUtiliz) {
		this.linCreditoUtiliz = linCreditoUtiliz;
	}

	@Column(name = "lin_credito_f_utiliz", scale = 4)
	public BigDecimal getLinCreditoFUtiliz() {
		return this.linCreditoFUtiliz;
	}

	public void setLinCreditoFUtiliz(BigDecimal linCreditoFUtiliz) {
		this.linCreditoFUtiliz = linCreditoFUtiliz;
	}

	@Column(name = "giro_cliente")
	public String getGiroCliente() {
		return this.giroCliente;
	}

	public void setGiroCliente(String giroCliente) {
		this.giroCliente = giroCliente;
	}

	@Column(name = "seguro_pesos", scale = 4)
	public BigDecimal getSeguroPesos() {
		return this.seguroPesos;
	}

	public void setSeguroPesos(BigDecimal seguroPesos) {
		this.seguroPesos = seguroPesos;
	}

	@Column(name = "seguro_uf", scale = 4)
	public BigDecimal getSeguroUf() {
		return this.seguroUf;
	}

	public void setSeguroUf(BigDecimal seguroUf) {
		this.seguroUf = seguroUf;
	}

	@Column(name = "estado_lc_kh", length = 15)
	@Length(max = 15)
	public String getEstadoLcKh() {
		return this.estadoLcKh;
	}

	public void setEstadoLcKh(String estadoLcKh) {
		this.estadoLcKh = estadoLcKh;
	}

	@Column(name = "estado_lc_cuotas", length = 15)
	@Length(max = 15)
	public String getEstadoLcCuotas() {
		return this.estadoLcCuotas;
	}

	public void setEstadoLcCuotas(String estadoLcCuotas) {
		this.estadoLcCuotas = estadoLcCuotas;
	}

	@Column(name = "observ_analista")
	public String getObservAnalista() {
		return this.observAnalista;
	}

	public void setObservAnalista(String observAnalista) {
		this.observAnalista = observAnalista;
	}

	@Column(name = "observ_solicitud")
	public String getObservSolicitud() {
		return this.observSolicitud;
	}

	public void setObservSolicitud(String observSolicitud) {
		this.observSolicitud = observSolicitud;
	}

	@Column(name = "secuencia_ejecutivo", precision = 18, scale = 0)
	public Long getSecuenciaEjecutivo() {
		return this.secuenciaEjecutivo;
	}

	public void setSecuenciaEjecutivo(Long secuenciaEjecutivo) {
		this.secuenciaEjecutivo = secuenciaEjecutivo;
	}

	@Column(name = "secuencia_analista", precision = 18, scale = 0)
	public Long getSecuenciaAnalista() {
		return this.secuenciaAnalista;
	}

	public void setSecuenciaAnalista(Long secuenciaAnalista) {
		this.secuenciaAnalista = secuenciaAnalista;
	}

	@Column(name = "secuencia_aprobador", precision = 18, scale = 0)
	public Long getSecuenciaAprobador() {
		return this.secuenciaAprobador;
	}

	public void setSecuenciaAprobador(Long secuenciaAprobador) {
		this.secuenciaAprobador = secuenciaAprobador;
	}

	@Column(name = "dm_solicitud", length = 10)
	@Length(max = 10)
	public String getDmSolicitud() {
		return this.dmSolicitud;
	}

	public void setDmSolicitud(String dmSolicitud) {
		this.dmSolicitud = dmSolicitud;
	}

	@Column(name = "canal", length = 30)
	@Length(max = 30)
	public String getCanal() {
		return this.canal;
	}

	public void setCanal(String canal) {
		this.canal = canal;
	}

	@Column(name = "tipo_cliente")
	public String getTipoCliente() {
		return this.tipoCliente;
	}

	public void setTipoCliente(String tipoCliente) {
		this.tipoCliente = tipoCliente;
	}

	@Column(name = "dm_venta", length = 250)
	@Length(max = 250)
	public String getDmVenta() {
		return this.dmVenta;
	}

	public void setDmVenta(String dmVenta) {
		this.dmVenta = dmVenta;
	}

	@Column(name = "des_tiposol", length = 50)
	@Length(max = 50)
	public String getDesTiposol() {
		return this.desTiposol;
	}

	public void setDesTiposol(String desTiposol) {
		this.desTiposol = desTiposol;
	}

	@Column(name = "tip_tiposol", length = 3)
	@Length(max = 3)
	public String getTipTiposol() {
		return this.tipTiposol;
	}

	public void setTipTiposol(String tipTiposol) {
		this.tipTiposol = tipTiposol;
	}

	@Column(name = "monto", scale = 4)
	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	@Column(name = "sub_tiposol", length = 50)
	@Length(max = 50)
	public String getSubTiposol() {
		return this.subTiposol;
	}

	public void setSubTiposol(String subTiposol) {
		this.subTiposol = subTiposol;
	}

	@Column(name = "evaluar", nullable = true)
	public Boolean getEvaluar() {
		return this.evaluar;
	}

	public void setEvaluar(Boolean evaluar) {
		this.evaluar = evaluar;
	}
	@Column(name = "devolver", nullable = true)
	public Boolean getDevolver() {
		return this.devolver;
	}

	public void setDevolver(Boolean devolver) {
		this.devolver = devolver;
	}
	
	@Column(name = "analizar", nullable = true)
	public Boolean getAnalizar() {
		return this.analizar;
	}

	public void setAnalizar(Boolean analizar) {
		this.analizar = analizar;
	}
	
	@Column(name = "cod_usuario_devuelve", nullable = true, length = 20)
	@Length(max = 20)
	public String getUsuarioDevuelve() {
		return this.usuarioDevuelve;
	}

	public void setUsuarioDevuelve(String usuarioDevuelve) {
		this.usuarioDevuelve = usuarioDevuelve;
	}
	
	@Column(name = "forma_pago", nullable = true, length = 100)
	@Length(max = 100)
	public String getFormaPago() {
		return this.formaPago;
	}

	public void setFormaPago(String formaPago) {
		this.formaPago = formaPago;
	}
	
	@Column(name = "hora_minuto_segundo", nullable = true, length = 100)
	@Length(max = 100)
	public String getHoraMinutosSegundos() {
		return this.horaMinutosSegundos;
	}

	public void setHoraMinutosSegundos(String horaMinutosSegundos) {
		this.horaMinutosSegundos = horaMinutosSegundos;
	}	

	@Column(name = "estado_evalaucion", nullable = true, length = 2)
	@Length(max = 2)
	public String getEstadoEvaluacion() {
		return this.estadoEvalaucion;
	}

	public void setEstadoEvaluacion(String estadoEvalaucion) {
		this.estadoEvalaucion = estadoEvalaucion;
	}	
	
	@Column(name = "monto_riesgo_kupfer_calculado", scale = 4, nullable = true)
	public BigDecimal getMontoRiesgoKupferCalculado() {
		return this.montoRiesgoKupferCalculado;
	}

	public void setMontoRiesgoKupferCalculado(BigDecimal montoRiesgoKupferCalculado) {
		this.montoRiesgoKupferCalculado = montoRiesgoKupferCalculado;
	}
	@Column(name = "usuario_varios", length = 15)
	@Length(max = 15)
	public String getUsuarioVarios() {
		return this.usuarioVarios;
	}

	public void setUsuarioVarios(String usuarioVarios) {
		this.usuarioVarios = usuarioVarios;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sociedad", nullable = true)
	public Sociedad getSociedad() {
		return sociedad;
	}

	public void setSociedad(Sociedad sociedad) {
		this.sociedad = sociedad;
	}
}
