package org.domain.sck.entity;

// Generated 04-dic-2012 12:34:55 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * LcredUsuarioNivelEncId generated by hbm2java
 */
@Embeddable
public class LcredUsuarioNivelEncId implements java.io.Serializable {

	private String idUsuario;
	private String nombreUsuario;
	private String correo;
	private String cargo;
	private Character administrador;
	private Character envioAutomOtrasSolc;

	public LcredUsuarioNivelEncId() {
	}

	public LcredUsuarioNivelEncId(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	public LcredUsuarioNivelEncId(String idUsuario, String nombreUsuario,
			String correo, String cargo, Character administrador,
			Character envioAutomOtrasSolc) {
		this.idUsuario = idUsuario;
		this.nombreUsuario = nombreUsuario;
		this.correo = correo;
		this.cargo = cargo;
		this.administrador = administrador;
		this.envioAutomOtrasSolc = envioAutomOtrasSolc;
	}

	@Column(name = "id_usuario", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "nombre_usuario", length = 200)
	@Length(max = 200)
	public String getNombreUsuario() {
		return this.nombreUsuario;
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

	@Column(name = "correo", length = 100)
	@Length(max = 100)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "cargo", length = 3)
	@Length(max = 3)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@Column(name = "administrador", length = 1)
	public Character getAdministrador() {
		return this.administrador;
	}

	public void setAdministrador(Character administrador) {
		this.administrador = administrador;
	}

	@Column(name = "envio_autom_otras_solc", length = 1)
	public Character getEnvioAutomOtrasSolc() {
		return this.envioAutomOtrasSolc;
	}

	public void setEnvioAutomOtrasSolc(Character envioAutomOtrasSolc) {
		this.envioAutomOtrasSolc = envioAutomOtrasSolc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LcredUsuarioNivelEncId))
			return false;
		LcredUsuarioNivelEncId castOther = (LcredUsuarioNivelEncId) other;

		return ((this.getIdUsuario() == castOther.getIdUsuario()) || (this
				.getIdUsuario() != null && castOther.getIdUsuario() != null && this
				.getIdUsuario().equals(castOther.getIdUsuario())))
				&& ((this.getNombreUsuario() == castOther.getNombreUsuario()) || (this
						.getNombreUsuario() != null
						&& castOther.getNombreUsuario() != null && this
						.getNombreUsuario()
						.equals(castOther.getNombreUsuario())))
				&& ((this.getCorreo() == castOther.getCorreo()) || (this
						.getCorreo() != null && castOther.getCorreo() != null && this
						.getCorreo().equals(castOther.getCorreo())))
				&& ((this.getCargo() == castOther.getCargo()) || (this
						.getCargo() != null && castOther.getCargo() != null && this
						.getCargo().equals(castOther.getCargo())))
				&& ((this.getAdministrador() == castOther.getAdministrador()) || (this
						.getAdministrador() != null
						&& castOther.getAdministrador() != null && this
						.getAdministrador()
						.equals(castOther.getAdministrador())))
				&& ((this.getEnvioAutomOtrasSolc() == castOther
						.getEnvioAutomOtrasSolc()) || (this
						.getEnvioAutomOtrasSolc() != null
						&& castOther.getEnvioAutomOtrasSolc() != null && this
						.getEnvioAutomOtrasSolc().equals(
								castOther.getEnvioAutomOtrasSolc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdUsuario() == null ? 0 : this.getIdUsuario().hashCode());
		result = 37
				* result
				+ (getNombreUsuario() == null ? 0 : this.getNombreUsuario()
						.hashCode());
		result = 37 * result
				+ (getCorreo() == null ? 0 : this.getCorreo().hashCode());
		result = 37 * result
				+ (getCargo() == null ? 0 : this.getCargo().hashCode());
		result = 37
				* result
				+ (getAdministrador() == null ? 0 : this.getAdministrador()
						.hashCode());
		result = 37
				* result
				+ (getEnvioAutomOtrasSolc() == null ? 0 : this
						.getEnvioAutomOtrasSolc().hashCode());
		return result;
	}

}
