package org.domain.sck.entity;

// Generated 04-ene-2013 17:17:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * LcredSolicitudVtapuntual generated by hbm2java
 */
@Entity
@Table(name = "lcred_solicitud_vtapuntual")
public class LcredSolicitudVtapuntual {

	private long numSolicitud;
	private String codTipoSolicitud;
	private String statusSolicitud;
	private Character tipoVentaInicial;
	private BigDecimal montoInicial;
	private Character tipoVentaFinal;
	private BigDecimal montoFinal;
	private String observacionesInicial;
	private String observacionesFinal;
	private String usuarioAnalisis;
	private Date fechaAnalisis;
	private Date horaAnalisis;
	private String motivoRechazo;
	private String observacionesRechazo;
	private String dcProducto;
	private String dcPlazo;
	private String dcMargen;
	private String dcMotivo;
	private BigDecimal montoPieInicial;
	private BigDecimal montoPieFinal;

	public LcredSolicitudVtapuntual() {
	}

	public LcredSolicitudVtapuntual(long numSolicitud) {
		this.numSolicitud = numSolicitud;
	}

	public LcredSolicitudVtapuntual(long numSolicitud, String codTipoSolicitud,
			String statusSolicitud, Character tipoVentaInicial,
			BigDecimal montoInicial, Character tipoVentaFinal,
			BigDecimal montoFinal, String observacionesInicial,
			String observacionesFinal, String usuarioAnalisis,
			Date fechaAnalisis, Date horaAnalisis, String motivoRechazo,
			String observacionesRechazo, String dcProducto,
			String dcPlazo, String dcMargen, String dcMotivo,
			BigDecimal montoPieInicial, BigDecimal montoPieFinal) {
		this.numSolicitud = numSolicitud;
		this.codTipoSolicitud = codTipoSolicitud;
		this.statusSolicitud = statusSolicitud;
		this.tipoVentaInicial = tipoVentaInicial;
		this.montoInicial = montoInicial;
		this.tipoVentaFinal = tipoVentaFinal;
		this.montoFinal = montoFinal;
		this.observacionesInicial = observacionesInicial;
		this.observacionesFinal = observacionesFinal;
		this.usuarioAnalisis = usuarioAnalisis;
		this.fechaAnalisis = fechaAnalisis;
		this.horaAnalisis = horaAnalisis;
		this.motivoRechazo = motivoRechazo;
		this.observacionesRechazo = observacionesRechazo;
		this.dcProducto = dcProducto;
		this.dcPlazo = dcPlazo;
		this.dcMargen = dcMargen;
		this.dcMotivo = dcMotivo;
		this.montoPieInicial = montoPieInicial;
		this.montoPieFinal = montoPieFinal;
	}

	@Id
	@Column(name = "num_solicitud", unique = true, nullable = false, precision = 18, scale = 0)
	public long getNumSolicitud() {
		return this.numSolicitud;
	}

	public void setNumSolicitud(long numSolicitud) {
		this.numSolicitud = numSolicitud;
	}

	@Column(name = "cod_tipo_solicitud", length = 3)
	@Length(max = 3)
	public String getCodTipoSolicitud() {
		return this.codTipoSolicitud;
	}

	public void setCodTipoSolicitud(String codTipoSolicitud) {
		this.codTipoSolicitud = codTipoSolicitud;
	}

	@Column(name = "status_solicitud", length = 2)
	@Length(max = 2)
	public String getStatusSolicitud() {
		return this.statusSolicitud;
	}

	public void setStatusSolicitud(String statusSolicitud) {
		this.statusSolicitud = statusSolicitud;
	}

	@Column(name = "tipo_venta_inicial", length = 1)
	public Character getTipoVentaInicial() {
		return this.tipoVentaInicial;
	}

	public void setTipoVentaInicial(Character tipoVentaInicial) {
		this.tipoVentaInicial = tipoVentaInicial;
	}

	@Column(name = "monto_inicial", scale = 4)
	public BigDecimal getMontoInicial() {
		return this.montoInicial;
	}

	public void setMontoInicial(BigDecimal montoInicial) {
		this.montoInicial = montoInicial;
	}

	@Column(name = "tipo_venta_final", length = 1)
	public Character getTipoVentaFinal() {
		return this.tipoVentaFinal;
	}

	public void setTipoVentaFinal(Character tipoVentaFinal) {
		this.tipoVentaFinal = tipoVentaFinal;
	}

	@Column(name = "monto_final", scale = 4)
	public BigDecimal getMontoFinal() {
		return this.montoFinal;
	}

	public void setMontoFinal(BigDecimal montoFinal) {
		this.montoFinal = montoFinal;
	}

	@Column(name = "observaciones_inicial")
	public String getObservacionesInicial() {
		return this.observacionesInicial;
	}

	public void setObservacionesInicial(String observacionesInicial) {
		this.observacionesInicial = observacionesInicial;
	}

	@Column(name = "observaciones_final")
	public String getObservacionesFinal() {
		return this.observacionesFinal;
	}

	public void setObservacionesFinal(String observacionesFinal) {
		this.observacionesFinal = observacionesFinal;
	}

	@Column(name = "usuario_analisis", length = 15)
	@Length(max = 15)
	public String getUsuarioAnalisis() {
		return this.usuarioAnalisis;
	}

	public void setUsuarioAnalisis(String usuarioAnalisis) {
		this.usuarioAnalisis = usuarioAnalisis;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_analisis", length = 23)
	public Date getFechaAnalisis() {
		return this.fechaAnalisis;
	}

	public void setFechaAnalisis(Date fechaAnalisis) {
		this.fechaAnalisis = fechaAnalisis;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hora_analisis", length = 23)
	public Date getHoraAnalisis() {
		return this.horaAnalisis;
	}

	public void setHoraAnalisis(Date horaAnalisis) {
		this.horaAnalisis = horaAnalisis;
	}

	@Column(name = "motivo_rechazo", length = 100)
	@Length(max = 100)
	public String getMotivoRechazo() {
		return this.motivoRechazo;
	}

	public void setMotivoRechazo(String motivoRechazo) {
		this.motivoRechazo = motivoRechazo;
	}

	@Column(name = "observaciones_rechazo")
	public String getObservacionesRechazo() {
		return this.observacionesRechazo;
	}

	public void setObservacionesRechazo(String observacionesRechazo) {
		this.observacionesRechazo = observacionesRechazo;
	}

	@Lob
	@Column(name = "dc_producto", nullable = false, length = 65535)
	@NotNull
	@Length(max = 65535)
	public String getDcProducto() {
		return this.dcProducto;
	}

	public void setDcProducto(String dcProducto) {
		this.dcProducto = dcProducto;
	}

	@Column(name = "dc_plazo", length = 50)
	@Length(max = 50)
	public String getDcPlazo() {
		return this.dcPlazo;
	}

	public void setDcPlazo(String dcPlazo) {
		this.dcPlazo = dcPlazo;
	}

	@Column(name = "dc_margen", length = 50)
	@Length(max = 50)
	public String getDcMargen() {
		return this.dcMargen;
	}

	public void setDcMargen(String dcMargen) {
		this.dcMargen = dcMargen;
	}

	@Column(name = "dc_motivo")
	public String getDcMotivo() {
		return this.dcMotivo;
	}

	public void setDcMotivo(String dcMotivo) {
		this.dcMotivo = dcMotivo;
	}

	@Column(name = "monto_pie_inicial", scale = 4)
	public BigDecimal getMontoPieInicial() {
		return this.montoPieInicial;
	}

	public void setMontoPieInicial(BigDecimal montoPieInicial) {
		this.montoPieInicial = montoPieInicial;
	}

	@Column(name = "monto_pie_final", scale = 4)
	public BigDecimal getMontoPieFinal() {
		return this.montoPieFinal;
	}

	public void setMontoPieFinal(BigDecimal montoPieFinal) {
		this.montoPieFinal = montoPieFinal;
	}

}
