package org.domain.sck.entity;

// Generated 07-05-2013 05:44:56 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * LcredArchivoAdjuntosId generated by hbm2java
 */
@Embeddable
public class LcredArchivoAdjuntosId implements java.io.Serializable {

	private long numSolicitud;
	private String codTipoSolicitud;
	private String archivoAdjunto;

	public LcredArchivoAdjuntosId() {
	}

	public LcredArchivoAdjuntosId(long numSolicitud, String codTipoSolicitud,
			String archivoAdjunto) {
		this.numSolicitud = numSolicitud;
		this.codTipoSolicitud = codTipoSolicitud;
		this.archivoAdjunto = archivoAdjunto;
	}

	@Column(name = "num_solicitud", nullable = false, precision = 18, scale = 0)
	public long getNumSolicitud() {
		return this.numSolicitud;
	}

	public void setNumSolicitud(long numSolicitud) {
		this.numSolicitud = numSolicitud;
	}

	@Column(name = "cod_tipo_solicitud", nullable = false, length = 3)
	@NotNull
	@Length(max = 3)
	public String getCodTipoSolicitud() {
		return this.codTipoSolicitud;
	}

	public void setCodTipoSolicitud(String codTipoSolicitud) {
		this.codTipoSolicitud = codTipoSolicitud;
	}

	@Column(name = "archivo_adjunto", nullable = false, length = 300)
	@NotNull
	@Length(max = 300)
	public String getArchivoAdjunto() {
		return this.archivoAdjunto;
	}

	public void setArchivoAdjunto(String archivoAdjunto) {
		this.archivoAdjunto = archivoAdjunto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LcredArchivoAdjuntosId))
			return false;
		LcredArchivoAdjuntosId castOther = (LcredArchivoAdjuntosId) other;

		return (this.getNumSolicitud() == castOther.getNumSolicitud())
				&& ((this.getCodTipoSolicitud() == castOther
						.getCodTipoSolicitud()) || (this.getCodTipoSolicitud() != null
						&& castOther.getCodTipoSolicitud() != null && this
						.getCodTipoSolicitud().equals(
								castOther.getCodTipoSolicitud())))
				&& ((this.getArchivoAdjunto() == castOther.getArchivoAdjunto()) || (this
						.getArchivoAdjunto() != null
						&& castOther.getArchivoAdjunto() != null && this
						.getArchivoAdjunto().equals(
								castOther.getArchivoAdjunto())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getNumSolicitud();
		result = 37
				* result
				+ (getCodTipoSolicitud() == null ? 0 : this
						.getCodTipoSolicitud().hashCode());
		result = 37
				* result
				+ (getArchivoAdjunto() == null ? 0 : this.getArchivoAdjunto()
						.hashCode());
		return result;
	}

}
