package org.domain.sck.entity;

// Generated 08-feb-2013 11:01:17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * LcredPerfiles generated by hbm2java
 */
@Entity
@Table(name = "lcred_perfiles")
public class LcredPerfiles implements java.io.Serializable {

	private String codPerfil;
	private String desPerfil;

	public LcredPerfiles() {
	}

	public LcredPerfiles(String codPerfil) {
		this.codPerfil = codPerfil;
	}

	public LcredPerfiles(String codPerfil, String desPerfil) {
		this.codPerfil = codPerfil;
		this.desPerfil = desPerfil;
	}

	@Id
	@Column(name = "cod_perfil", unique = true, nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getCodPerfil() {
		return this.codPerfil;
	}

	public void setCodPerfil(String codPerfil) {
		this.codPerfil = codPerfil;
	}

	@Column(name = "des_perfil", length = 30)
	@Length(max = 30)
	public String getDesPerfil() {
		return this.desPerfil;
	}

	public void setDesPerfil(String desPerfil) {
		this.desPerfil = desPerfil;
	}

}
