package org.domain.sck.entity;

// Generated 04-sep-2012 11:19:31 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name = "motivo_rechazo_cheque")
public class MotivoRechazoCheque implements java.io.Serializable {

	private String codigo;
	private String descripcion;

	public MotivoRechazoCheque() {
	}

	public MotivoRechazoCheque(String codigo) {
		this.codigo = codigo;
	}

	public MotivoRechazoCheque(String codigo, String descripcion) {
		this.codigo = codigo;
		this.descripcion = descripcion;
	}

	@Id
	@Column(name = "codigo", unique = true, nullable = false, length = 3)
	@NotNull
	@Length(max = 2)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descripcion", length = 100)
	@Length(max = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}


}
