package org.domain.sck.entity;

// Generated 04-sep-2012 11:19:31 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Provincia generated by hbm2java
 */
@Entity
@Table(name = "provincia")
public class Provincia implements java.io.Serializable {

	private String codigo;
	private String descripcion;
	private Region region;

	public Provincia() {
	}

	public Provincia(String codigo) {
		this.codigo = codigo;
	}

	public Provincia(String codigo, String descripcion, Region region) {
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.region = region;
	}

	@Id
	@Column(name = "codigo", unique = true, nullable = false, length = 5)
	@NotNull
	@Length(max = 5)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descripcion", length = 100)
	@Length(max = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "region", nullable = false)
	@NotNull
	public Region getRegion() {
		return region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}	
	
	

}
