package org.domain.sck.entity;

// Generated 02-10-2012 09:54:39 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.NotNull;

/**
 * FormaPago generated by hbm2java
 */
@Entity
@Table(name = "sociedad")
public class Sociedad {

	private long idSociedad;
	private String codigoSociedad;
	private String rut;
	private String razonSocial;
	
	public Sociedad() {
	}

	public Sociedad(Long idSociedad, String codigo_sociedad, String rut, String razon_social) {
		this.idSociedad = idSociedad;
		this.codigoSociedad = codigo_sociedad;
		this.rut = rut;
		this.razonSocial = razon_social;
		
	}

	@Id
	@GenericGenerator(name = "sociedadAuxSequenceGenerator", strategy = "org.hibernate.id.enhanced.TableGenerator", parameters = {
			@Parameter(name = "table_name", value = "hibernate_sequences"),
			@Parameter(name = "segment_value", value = "SEQ_SOCIEDAD_AUX"),
			@Parameter(name = "initial_value", value = "1"),
			@Parameter(name = "increment_size", value = "1") })
	@GeneratedValue(generator = "sociedadAuxSequenceGenerator")
	
	@Column(name = "id_sociedad", unique = true, nullable = false, precision = 18, scale = 0)
	public Long getIdSociedad() {
		return this.idSociedad;
	}

	public void setIdSociedad(Long idSociedad) {
		this.idSociedad = idSociedad;
	}
	

	@Column(name = "codigo_sociedad", nullable = false)
	@NotNull
	public String getCodigoSociedad() {
		return this.codigoSociedad;
	}

	public void setCodigoSociedad(String codigoSociedad) {
		this.codigoSociedad = codigoSociedad;
	}

	@Column(name = "rut", nullable = false)
	@NotNull
	public String getRut() {
		return this.rut;
	}

	public void setRut(String rut) {
		this.rut = rut;
	}

	@Column(name = "razon_social", nullable = false)
	@NotNull
	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}


	
}
