package org.domain.sck.entity;

// Generated 17-ene-2013 12:02:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ConceptosNegocio generated by hbm2java
 */
@Entity
@Table(name = "solicitud_logs")
public class SolicitudLogs {

	private long systemId;
	private Long idSolicitud;
	private String usuario;
	private Date fechaHora;
	private String codigoEstado;
	private String descripcionEstado;
	private String accion;

	public SolicitudLogs() {
	}


	public SolicitudLogs(long systemId, Long idSolicitud, String emisor, String usuario,
			Date fechaHora, String codigoEstado, String descripcionEstado, String accion) {
		this.systemId = systemId;
		this.idSolicitud = idSolicitud;
		this.usuario = usuario;
		this.fechaHora = fechaHora;
		this.codigoEstado = codigoEstado;
		this.descripcionEstado = descripcionEstado;
		this.accion = accion;
	}

	@Id
	@Column(name = "system_id", unique = true, nullable = false, precision = 18, scale = 0)
	public long getSystemId() {
		return this.systemId;
	}

	public void setSystemId(long systemId) {
		this.systemId = systemId;
	}

	
	@Column(name = "solicitud_id", nullable = false, precision = 18, scale = 0)
	public Long getIdSolicitud() {
		return idSolicitud;
	}


	public void setIdSolicitud(Long idSolicitud) {
		this.idSolicitud = idSolicitud;
	}
	
	
	@Column(name = "usuario", nullable = false, length = 50)
	@Length(max = 50)	
	public String getUsuario() {
		return usuario;
	}


	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_hora", nullable = false)	
	public Date getFechaHora() {
		return fechaHora;
	}


	public void setFechaHora(Date fechaHora) {
		this.fechaHora = fechaHora;
	}

	@Column(name = "codigo_estado", nullable = false)	
	public String getCodigoEstado() {
		return codigoEstado;
	}

	public void setCodigoEstado(String codigoEstado) {
		this.codigoEstado = codigoEstado;
	}	
	
	
	@Column(name = "descripcion_estado", nullable = false, length = 30)
	@NotNull
	@Length(max = 30)
	public String getDescripcionEstado() {
		return descripcionEstado;
	}


	public void setDescripcionEstado(String descripcionEstado) {
		this.descripcionEstado = descripcionEstado;
	}

	@Column(name = "accion", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getAccion() {
		return accion;
	}


	public void setAccion(String accion) {
		this.accion = accion;
	}



	
	
	
	
	
}
