package org.domain.sck.entity;

// Generated 17-ene-2013 12:02:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * SolicitudAccion generated by hbm2java
 */
@Entity
@Table(name = "solicitud_accion")
public class SolicitudAccion {

	private long systemId;
	private Long idSolicitud;
	private Date fechaInicial;
	private Date fechaFinal;
	private String usuario;
	private Accion accion;
	private Long diffSeconds;
	private Long diffMinutes;
	private Long diffHours;

	public SolicitudAccion() {

	}

	public SolicitudAccion(long systemId, Long idSolicitud,Date fechaInicial, Date fechaFinal,String usuario, Accion accion,
			Long diffSeconds, Long diffMinutes, Long diffHours) {
		this.systemId = systemId;
		this.idSolicitud = idSolicitud;
		this.fechaInicial = fechaInicial;
		this.fechaFinal = fechaFinal;
		this.usuario = usuario;
		this.accion = accion;
		this.diffSeconds = diffSeconds;
		this.diffMinutes = diffMinutes;
		this.diffHours = diffHours;
		
	}

	@Id
	@Column(name = "system_id", unique = true, nullable = false, precision = 18, scale = 0)
	public long getSystemId() {
		return this.systemId;
	}
	public void setSystemId(long systemId) {
		this.systemId = systemId;
	}

	
	@Column(name = "solicitud_id", nullable = false, precision = 18, scale = 0)
	public Long getIdSolicitud() {
		return idSolicitud;
	}
	public void setIdSolicitud(Long idSolicitud) {
		this.idSolicitud = idSolicitud;
	}
	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_inicial", nullable = false)	
	public Date getFechaInicial() {
		return fechaInicial;
	}

	public void setFechaInicial(Date fechaInicial) {
		this.fechaInicial = fechaInicial;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_final", nullable = false)	
	public Date getFechaFinal() {
		return fechaFinal;
	}

	public void setFechaFinal(Date fechaFinal) {
		this.fechaFinal = fechaFinal;
	}
	
	@Column(name = "usuario", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsuario() {
		return usuario;
	}
	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accion_id", nullable = false)
	@NotNull
	public Accion getAccion() {
		return accion;
	}

	public void setAccion(Accion accion) {
		this.accion = accion;
	}
	
	@Column(name = "diffSeconds", nullable = true, length = 50)
	@Length(max = 50)	
	public Long getDiffSeconds() {
		return diffSeconds;
	}
	public void setDiffSeconds(Long diffSeconds) {
		this.diffSeconds = diffSeconds;
	}
	

	@Column(name = "diffMinutes", nullable = true, length = 50)
	@Length(max = 50)	
	public Long getDiffMinutes() {
		return diffMinutes;
	}
	public void setDiffMinutes(Long diffMinutes) {
		this.diffMinutes = diffMinutes;
	}


	@Column(name = "diffHours", nullable = true, length = 50)
	@Length(max = 50)	
	public Long getDiffHours() {
		return diffHours;
	}
	public void setDiffHours(Long diffHours) {
		this.diffHours = diffHours;
	}
	
}
