package org.domain.sck.entity;

// Generated 17-ene-2013 12:02:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ConceptosNegocio generated by hbm2java
 */
@Entity
@Table(name = "solicitud_usuario_derivada")
public class SolicitudUsuarioDerivada {

	private long systemId;
	private Long idSolicitud;
	private Usuariosegur usuario;
	private LcredEstado estado;
	private Date fechaHora;
	private Boolean confirmacionObligatoria;
	private Boolean confirmacion;
	private String codEstadoDerivada;
	private String usernameAutorizacion;
	@Transient private String apruebaRechazo;

	

	public SolicitudUsuarioDerivada() {
	}


	public SolicitudUsuarioDerivada(long systemId, Long idSolicitud, Usuariosegur usuario, LcredEstado estado,
			Date fechaHora, Boolean confirmacionObligatoria, Boolean confirmacion,String codEstadoDerivada,String usernameAutorizacion) {
		this.systemId = systemId;
		this.idSolicitud = idSolicitud;
		this.usuario = usuario;
		this.estado = estado;
		this.fechaHora = fechaHora;
		this.confirmacionObligatoria = confirmacionObligatoria;
		this.confirmacion = confirmacion;
		this.codEstadoDerivada = codEstadoDerivada;
		this.usernameAutorizacion = usernameAutorizacion;
	}




	@Id
	@Column(name = "system_id", unique = true, nullable = false, precision = 18, scale = 0)
	public long getSystemId() {
		return this.systemId;
	}

	public void setSystemId(long systemId) {
		this.systemId = systemId;
	}

	
	@Column(name = "solicitud_id", nullable = false, precision = 18, scale = 0)
	public Long getIdSolicitud() {
		return idSolicitud;
	}


	public void setIdSolicitud(Long idSolicitud) {
		this.idSolicitud = idSolicitud;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_id", nullable = false)
	@NotNull
	public Usuariosegur getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuariosegur usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estado_id", nullable = true)
	@NotNull
	public LcredEstado getEstado() {
		return estado;
	}

	public void setEstado(LcredEstado estado) {
		this.estado = estado;
	}	

	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_hora", nullable = false)	
	public Date getFechaHora() {
		return fechaHora;
	}

	public void setFechaHora(Date fechaHora) {
		this.fechaHora = fechaHora;
	}
	
	@Column(name = "confirmacion_obligatoria", nullable = false)
	public Boolean getConfirmacionObligatoria() {
		return this.confirmacionObligatoria;
	}

	public void setConfirmacionObligatoria(Boolean confirmacionObligatoria) {
		this.confirmacionObligatoria = confirmacionObligatoria;
	}
	
	@Column(name = "confirmacion", nullable = true)
	public Boolean getConfirmacion() {
		return this.confirmacion;
	}

	public void setConfirmacion(Boolean confirmacion) {
		this.confirmacion = confirmacion;
	}	
	
	@Column(name = "cod_estado_derivada", nullable = true, length = 2)
	@Length(max = 2)
	public String getCodEstadoDerivada() {
		return codEstadoDerivada;
	}


	public void setCodEstadoDerivada(String codEstadoDerivada) {
		this.codEstadoDerivada = codEstadoDerivada;
	}

	
	@Column(name = "username_autorizacion", nullable = true, length = 100)
	@Length(max = 100)	
	public String getUsernameAutorizacion() {
		return usernameAutorizacion;
	}


	public void setUsernameAutorizacion(String usernameAutorizacion) {
		this.usernameAutorizacion = usernameAutorizacion;
	}

	@Transient
	public String getApruebaRechazo() {
		return apruebaRechazo;
	}

	@Transient
	public void setApruebaRechazo(String apruebaRechazo) {
		this.apruebaRechazo = apruebaRechazo;
	}
	
	
	
	
}
