package org.domain.sck.entity;

// Generated 04-sep-2012 15:55:56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Sucursal generated by hbm2java
 */
@Entity
@Table(name = "sucursal")
public class Sucursal implements java.io.Serializable {

	private String codigo;
	private String descripcion;
	private String sociedad;
	private String zona;
	private Character zona2;
	private String orden;
	private String codigobbx;

	public Sucursal() {
	}

	public Sucursal(String codigo, String descripcion) {
		this.codigo = codigo;
		this.descripcion = descripcion;
	}

	public Sucursal(String codigo, String descripcion, String sociedad,
			String zona, Character zona2, String orden, String codigobbx) {
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.sociedad = sociedad;
		this.zona = zona;
		this.zona2 = zona2;
		this.orden = orden;
		this.codigobbx = codigobbx;
	}

	@Id
	@Column(name = "codigo", unique = true, nullable = false, length = 4)
	@NotNull
	@Length(max = 4)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "sociedad", length = 10)
	@Length(max = 10)
	public String getSociedad() {
		return this.sociedad;
	}

	public void setSociedad(String sociedad) {
		this.sociedad = sociedad;
	}

	@Column(name = "zona", length = 2)
	@Length(max = 2)
	public String getZona() {
		return this.zona;
	}

	public void setZona(String zona) {
		this.zona = zona;
	}

	@Column(name = "zona2", length = 1)
	public Character getZona2() {
		return this.zona2;
	}

	public void setZona2(Character zona2) {
		this.zona2 = zona2;
	}

	@Column(name = "orden", length = 8)
	@Length(max = 8)
	public String getOrden() {
		return this.orden;
	}

	public void setOrden(String orden) {
		this.orden = orden;
	}

	@Column(name = "codigobbx", length = 2)
	@Length(max = 2)
	public String getCodigobbx() {
		return this.codigobbx;
	}

	public void setCodigobbx(String codigobbx) {
		this.codigobbx = codigobbx;
	}

}
