package org.domain.sck.entity;

// Generated 02-10-2012 09:54:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Ufs generated by hbm2java
 */
@Entity
@Table(name = "ufs")
public class Ufs {

	private Long idUfs;
	private Date fecha;
	private Double valor;
	private Double dolar;
	private Double euro;
	private Double utm;

	public Ufs() {
	}

	public Ufs(long idUfs, Date fecha, Double valor, Double dolar, Double euro, Double utm) {
		this.idUfs = idUfs;
		this.fecha = fecha;
		this.valor = valor;
		this.dolar = dolar;
		this.euro = euro;
		this.utm = utm;
	}

	@Id
	@GenericGenerator(name = "ufsSequenceGenerator", strategy = "org.hibernate.id.enhanced.TableGenerator", parameters = {
			@Parameter(name = "table_name", value = "hibernate_sequences"),
			@Parameter(name = "segment_value", value = "SEQ_UFS"),
			@Parameter(name = "initial_value", value = "1"),
			@Parameter(name = "increment_size", value = "1") })
			
			
	@GeneratedValue(generator = "ufsSequenceGenerator")
	@Column(name = "id_ufs", unique = true, nullable = false, precision = 18, scale = 0, columnDefinition = "numeric(18,0)")
	public Long getIdUfs() {
		return idUfs;
	}

	public void setIdUfs(Long idUfs) {
		this.idUfs = idUfs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="fecha", nullable = true )
	public Date getFecha() {
		return fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "valor", precision = 53, scale = 2)
	public Double getValor() {
		return this.valor;
	}

	public void setValor(Double valor) {
		this.valor = valor;
	}

	@Column(name = "dolar", precision = 53, scale = 2)
	public Double getDolar() {
		return this.dolar;
	}

	public void setDolar(Double dolar) {
		this.dolar = dolar;
	}
	
	@Column(name = "euro", precision = 53, scale = 2)
	public Double getEuro() {
		return this.euro;
	}

	public void setEuro(Double euro) {
		this.euro = euro;
	}
	
	
	@Column(name = "utm", precision = 53, scale = 2)
	public Double getUtm() {
		return this.utm;
	}

	public void setUtm(Double utm) {
		this.utm = utm;
	}	
	

	
}
