package org.domain.sck.entity;

// Generated 02-10-2012 09:54:39 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * UsuarioTipo generated by hbm2java
 */
@Entity
@Table(name = "usuario_tipo")
public class UsuarioTipo implements java.io.Serializable{

	private long idUsuarioTipo;
	private Usuariosegur usuario;
	private TipoUsuario tipoUsuario;

	public UsuarioTipo() {
	}

	public UsuarioTipo(long idUsuarioTipo, Usuariosegur usuario,TipoUsuario tipoUsuario) {
		this.idUsuarioTipo = idUsuarioTipo;
		this.usuario = usuario;
		this.tipoUsuario = tipoUsuario;
	}

	@Id
	@GenericGenerator(name = "usuarioTipoSequenceGenerator", strategy = "org.hibernate.id.enhanced.TableGenerator", parameters = {
			@Parameter(name = "table_name", value = "hibernate_sequences"),
			@Parameter(name = "segment_value", value = "SEQ_USUARIO_TIPO"),
			@Parameter(name = "initial_value", value = "1"),
			@Parameter(name = "increment_size", value = "1") })
			
			
	@GeneratedValue(generator = "usuarioTipoSequenceGenerator")
	@Column(name = "idUsuarioTipo", unique = true, nullable = false, precision = 18, scale = 0)
	public Long getIdUsuarioTipo() {
		return idUsuarioTipo;
	}

	public void setIdUsuarioTipo(Long idUsuarioTipo) {
		this.idUsuarioTipo = idUsuarioTipo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_id", nullable = false)
	@NotNull
	public Usuariosegur getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuariosegur usuario) {
		this.usuario = usuario;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipoUsuario_id", nullable = false)
	@NotNull
	public TipoUsuario getTipoUsuario() {
		return tipoUsuario;
	}

	public void setTipoUsuario(TipoUsuario tipoUsuario) {
		this.tipoUsuario = tipoUsuario;
	}	
	
}
