package org.domain.sck.entity;

// Generated 02-10-2012 09:54:39 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * UsuarioPerfil generated by hbm2java
 */
@Entity
@Table(name = "usuario_perfil")
public class UsuarioPerfil implements java.io.Serializable{

	private long idUsuarioPerfil;
	private Usuariosegur usuario;
	private LcredPerfiles perfil;

	public UsuarioPerfil() {
	}

	public UsuarioPerfil(long idUsuarioPerfil, Usuariosegur usuario, LcredPerfiles perfil) {
		this.idUsuarioPerfil = idUsuarioPerfil;
		this.usuario = usuario;
		this.perfil = perfil;
	}

	@Id
	@GenericGenerator(name = "usuarioPerfilSequenceGenerator", strategy = "org.hibernate.id.enhanced.TableGenerator", parameters = {
			@Parameter(name = "table_name", value = "hibernate_sequences"),
			@Parameter(name = "segment_value", value = "SEQ_USUARIO_PERFIL"),
			@Parameter(name = "initial_value", value = "1"),
			@Parameter(name = "increment_size", value = "1") })
			
			
	@GeneratedValue(generator = "usuarioPerfilSequenceGenerator")
	@Column(name = "idUsuarioTipo", unique = true, nullable = false, precision = 18, scale = 0)
	public Long getIdUsuarioPerfil() {
		return idUsuarioPerfil;
	}

	public void setIdUsuarioPerfil(Long idUsuarioPerfil) {
		this.idUsuarioPerfil = idUsuarioPerfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_username", nullable = false)
	@NotNull
	public Usuariosegur getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuariosegur usuario) {
		this.usuario = usuario;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "perfil_usuario_id", nullable = false)
	@NotNull
	public LcredPerfiles getPerfil() {
		return perfil;
	}

	public void setPerfil(LcredPerfiles perfil) {
		this.perfil = perfil;
	}	
	
}
