package org.domain.sck.entity;

// Generated 21-02-2013 11:56:59 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.Length;

/**
 * Usuariosegur generated by hbm2java
 */
@Entity
@Table(name = "USUARIOSEGUR")
public class Usuariosegur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idPersonal;
	private String alias;
	private String rut;
	private String nombre;
	private String correo;
	private String cargo;
	private String anexo;
	private String celular;
	private Integer marca;
	private Integer sucursal;
	private Integer negocio;
	private String password;
	private Character aprueba;
	private String anexoIp;
	private String ceco;
	private Character cajero;
	private String centro;
	private String descSuc;
	private Boolean obligatorio; 
	private Boolean eliminado; 

	public Usuariosegur() {
	}

	public Usuariosegur(long idPersonal) {
		this.idPersonal = idPersonal;
	}

	public Usuariosegur(long idPersonal, String alias, String rut,
			String nombre, String correo, String cargo, String anexo,
			String celular, Integer marca, Integer sucursal, Integer negocio,
			String password, Character aprueba, String anexoIp, String ceco,
			Character cajero, String centro, String descSuc, boolean obligatorio, Boolean eliminado) {
		this.idPersonal = idPersonal;
		this.alias = alias;
		this.rut = rut;
		this.nombre = nombre;
		this.correo = correo;
		this.cargo = cargo;
		this.anexo = anexo;
		this.celular = celular;
		this.marca = marca;
		this.sucursal = sucursal;
		this.negocio = negocio;
		this.password = password;
		this.aprueba = aprueba;
		this.anexoIp = anexoIp;
		this.ceco = ceco;
		this.cajero = cajero;
		this.centro = centro;
		this.descSuc = descSuc;
		this.obligatorio = obligatorio;
		this.eliminado = eliminado;
	}

	@Id
	@Column(name = "id_personal", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdPersonal() {
		return this.idPersonal;
	}

	public void setIdPersonal(long idPersonal) {
		this.idPersonal = idPersonal;
	}

	@Column(name = "Alias", length = 20)
	@Length(max = 20)
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Column(name = "Rut", length = 20)
	@Length(max = 20)
	public String getRut() {
		return this.rut;
	}

	public void setRut(String rut) {
		this.rut = rut;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Correo")
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "Cargo")
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@Column(name = "anexo", length = 20)
	@Length(max = 20)
	public String getAnexo() {
		return this.anexo;
	}

	public void setAnexo(String anexo) {
		this.anexo = anexo;
	}

	@Column(name = "celular", length = 20)
	@Length(max = 20)
	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	@Column(name = "marca")
	public Integer getMarca() {
		return this.marca;
	}

	public void setMarca(Integer marca) {
		this.marca = marca;
	}

	@Column(name = "sucursal")
	public Integer getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Integer sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "negocio")
	public Integer getNegocio() {
		return this.negocio;
	}

	public void setNegocio(Integer negocio) {
		this.negocio = negocio;
	}

	@Column(name = "Password", length = 20)
	@Length(max = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "aprueba", length = 1)
	public Character getAprueba() {
		return this.aprueba;
	}

	public void setAprueba(Character aprueba) {
		this.aprueba = aprueba;
	}

	@Column(name = "anexoIP", length = 20)
	@Length(max = 20)
	public String getAnexoIp() {
		return this.anexoIp;
	}

	public void setAnexoIp(String anexoIp) {
		this.anexoIp = anexoIp;
	}

	@Column(name = "ceco", length = 10)
	@Length(max = 10)
	public String getCeco() {
		return this.ceco;
	}

	public void setCeco(String ceco) {
		this.ceco = ceco;
	}

	@Column(name = "cajero", length = 1)
	public Character getCajero() {
		return this.cajero;
	}

	public void setCajero(Character cajero) {
		this.cajero = cajero;
	}

	@Column(name = "centro")
	public String getCentro() {
		return this.centro;
	}

	public void setCentro(String centro) {
		this.centro = centro;
	}

	@Column(name = "desc_suc", length = 100)
	@Length(max = 100)
	public String getDescSuc() {
		return this.descSuc;
	}

	public void setDescSuc(String descSuc) {
		this.descSuc = descSuc;
	}
	
	@Column(name = "obligatorio", nullable = true)
	public Boolean getObligatorio() {
		return this.obligatorio;
	}

	public void setObligatorio(Boolean obligatorio) {
		this.obligatorio = obligatorio;
	}
	
	@Column(name = "eliminado", nullable = true)
	public Boolean getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(Boolean eliminado) {
		this.eliminado = eliminado;
	}
	
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Usuariosegur that = (Usuariosegur) o;

        if (!alias.equals(that.alias)) return false;

        return true;
    }

    @Override
    public int hashCode() {
        return alias.hashCode();
    }
}
