package org.domain.sck.entity;

// Generated 01-feb-2013 12:39:20 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * LcredSolicitudProrroga generated by hbm2java
 */
@Entity
@Table(name = "lcred_solicitud_prorroga")
public class LcredSolicitudProrroga implements java.io.Serializable {

	private LcredSolicitudProrrogaId id;

	public LcredSolicitudProrroga() {
	}

	public LcredSolicitudProrroga(LcredSolicitudProrrogaId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "numSolicitud", column = @Column(name = "num_solicitud", nullable = false, precision = 18, scale = 0)),
			@AttributeOverride(name = "nroCheque", column = @Column(name = "nro_cheque", length = 20)),
			@AttributeOverride(name = "monto", column = @Column(name = "monto", scale = 4)),
			@AttributeOverride(name = "vencActual", column = @Column(name = "venc_actual", length = 10)),
			@AttributeOverride(name = "vencNuevo", column = @Column(name = "venc_nuevo", length = 10)) })
	@NotNull
	public LcredSolicitudProrrogaId getId() {
		return this.id;
	}

	public void setId(LcredSolicitudProrrogaId id) {
		this.id = id;
	}

}
