package org.domain.sck.entity;

// Generated 04-sep-2012 11:19:31 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Comuna generated by hbm2java
 */
@Entity
@Table(name = "comuna")
public class Comuna implements java.io.Serializable {

	private String codigo;
	private String descripcion;
	private Provincia provincia;

	public Comuna() {
	}

	public Comuna(String codigo) {
		this.codigo = codigo;
	}

	public Comuna(String codigo, String descripcion,Provincia provincia) {
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.provincia = provincia;
	}

	@Id
	@Column(name = "codigo", unique = true, nullable = false, length = 5)
	@NotNull
	@Length(max = 5)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descripcion", length = 100)
	@Length(max = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "provincia", nullable = true)
	@NotNull
	public Provincia getProvincia() {
		return provincia;
	}

	public void setProvincia(Provincia provincia) {
		this.provincia = provincia;
	}	
	
	

}
