package org.domain.sck.entity;

// Generated 02-10-2012 09:54:39 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.NotNull;

/**
 * FormaPago generated by hbm2java
 */
@Entity
@Table(name = "solicitud_dia_reparo")
public class SolicitudDiaReparo {

	private long idSolicitudDiaReparo;
	private String descripcion;
	private long dias;
	public SolicitudDiaReparo() {
	}

	public SolicitudDiaReparo(long idSolicitudDiaReparo, String descripcion, long dias) {
		this.idSolicitudDiaReparo = idSolicitudDiaReparo;
		this.descripcion = descripcion;
		this.dias = dias;
	}

	@Id
	@GenericGenerator(name = "solicitudDiaReparoSequenceGenerator", strategy = "org.hibernate.id.enhanced.TableGenerator", parameters = {
			@Parameter(name = "table_name", value = "hibernate_sequences"),
			@Parameter(name = "segment_value", value = "SEQ_SOLICITUD_DIA_REPARO"),
			@Parameter(name = "initial_value", value = "1"),
			@Parameter(name = "increment_size", value = "1") })
	@GeneratedValue(generator = "solicitudDiaReparoSequenceGenerator")
	@Column(name = "id_solicitud_dia_reparo", unique = true, nullable = false, precision = 18, scale = 0)
	public Long getIdSolicitudDiaReparo() {
		return this.idSolicitudDiaReparo;
	}

	public void setIdSolicitudDiaReparo(long idSolicitudDiaReparo) {
		this.idSolicitudDiaReparo = idSolicitudDiaReparo;
	}
	

	@Column(name = "descripcion", nullable = false)
	@NotNull
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}


	@Column(name = "dias", nullable = false)
	@NotNull
	public long getDias() {
		return dias;
	}

	public void setDias(long dias) {
		this.dias = dias;
	}	

}
