package org.domain.sck.entity;

// Generated 04-sep-2012 11:19:31 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * SolicitudUsuarioCorreo generated by hbm2java
 */
@Entity
@Table(name = "solicitud_usuario_correo")
public class SolicitudUsuarioCorreo  {

	private String username;
	private String nombre;
	private String correo;
	private boolean evaluar;
	private Boolean confirmar;


	public SolicitudUsuarioCorreo() {
	}

	public SolicitudUsuarioCorreo(String username) {
		this.username = username;
	}

	public SolicitudUsuarioCorreo(String username, String nombre, String correo,  boolean evaluar, Boolean confirmar) {
		this.username = username;
		this.nombre = nombre;
		this.correo = correo;
		this.evaluar = evaluar;
		this.confirmar = confirmar;
	}

	@Id
	@Column(name = "username", unique = true, nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "nombre", length = 100)
	@Length(max = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "correo", length = 50)
	@Length(max = 50)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "evaluar", nullable = true)
	public boolean getEvaluar() {
		return this.evaluar;
	}

	public void setEvaluar(boolean evaluar) {
		this.evaluar = evaluar;
	}
	
	@Column(name = "confirmar", nullable = true)
	public Boolean getConfirmar() {
		return this.confirmar;
	}

	public void setConfirmar(Boolean confirmar) {
		this.confirmar = confirmar;
	}

}
