package org.domain.sck.entity;

// Generated 29-05-2012 04:33:41 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * SolicitudConceptosNegocioLC generated by hbm2java
 */
@Entity
@Table(name = "solicitud_concepto_negocio_lc")
public class SolicitudConceptosNegocioLC {

	private long systemId;
	private LcredSolicitud solicitud;
	private ConceptosNegocio conceptosNegocio;
	private Long monto;

	public SolicitudConceptosNegocioLC() {
	}

	public SolicitudConceptosNegocioLC(long systemId, LcredSolicitud solicitud, ConceptosNegocio conceptosNegocio,
			Long monto) {
		this.systemId = systemId;
		this.solicitud = solicitud;
		this.conceptosNegocio = conceptosNegocio;
		this.monto = monto;
	}

	
	@Id
	@GenericGenerator(name="solConNegLcSequenceGenerator", strategy = "org.hibernate.id.enhanced.TableGenerator",
	    parameters = {
			@Parameter(name = "table_name", value = "hibernate_sequences"),
			@Parameter(name = "segment_value", value = "SEQ_SOLICITUD_CONCEPTO_NEGOCIO_LC"), 
	        @Parameter(name = "initial_value", value = "1"),
	        @Parameter(name = "increment_size", value = "1")
	    }
	)
	@GeneratedValue(generator = "solConNegLcSequenceGenerator")
	@Column(name = "system_id", unique = true, nullable = false, precision = 18, scale = 0,columnDefinition = "numeric(18,0)")
	public long getSystemId() {
		return this.systemId;
	}

	public void setSystemId(long systemId) {
		this.systemId = systemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns(value = {@JoinColumn(name = "solicitud_id", referencedColumnName="num_solicitud", columnDefinition = "numeric(18,0)"),
			              @JoinColumn(name = "fecha_solicitud", referencedColumnName = "fec_solicitud")})
	@NotNull
	public LcredSolicitud getSolicitud() {
		return this.solicitud;
	}

	public void setSolicitud(LcredSolicitud solicitud) {
		this.solicitud = solicitud;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "concepto_negocio_id")	
	public ConceptosNegocio getConceptosNegocio() {
		return conceptosNegocio;
	}

	public void setConceptosNegocio(ConceptosNegocio conceptosNegocio) {
		this.conceptosNegocio = conceptosNegocio;
	}	
	
	@Column(name = "monto", precision = 18, scale = 0)
	public Long getMonto() {
		return monto;
	}
	
	public void setMonto(Long monto) {
		this.monto = monto;
	}
	
	
	
}
